<?php

/**
 * @file
 * Common popup functionality for Ding!
 */

/**
 * Implements hook_library().
 */
function ding_popup_library() {
  $path = drupal_get_path('module', 'ding_popup');
  return array(
    'ding_popup' => array(
      'title' => 'Ding popup',
      'version' => '1.x',
      'js' => array(
        $path . '/ding_popup-popupbar.js' => array(
          'scope' => 'footer',
        ),
        $path . '/ding_popup.js' => array(
          'scope' => 'footer',
        ),
      ),
      'dependencies' => array(
        array(
          'system',
          'drupal.ajax',
        ),
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_html().
 */
function ding_popup_preprocess_html() {
  drupal_add_library('ding_popup', 'ding_popup', true);
}

/**
 * Ajax command to open a popup.
 */
function ajax_command_ding_popup($name, $title, $html, $options = array()) {
  global $user;
  $options += array(
    'resubmit' => FALSE,
    'extra_data' => array(),
    'refresh' => FALSE,
  );

  return array(
    'command' => 'ding_popup',
    'name' => $name,
    'title' => check_plain($title),
    'data' => $html,
    'resubmit' => (bool) $options['resubmit'],
    'extra_data' => $options['extra_data'],
    'refresh' => (bool) $options['refresh'],
  );
}

/**
 * Ajax command to close a popup.
 */
function ajax_command_ding_popup_close($name, $refresh = FALSE) {
  return array(
    'command' => 'ding_popup_close',
    'name' => $name,
    'refresh' => $refresh,
  );
}
