<?php
/**
 * DefaultApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DDB Cover Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation coverTypeGet
     *
     * Search covers
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string[] $id # ID A list of IDs. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list of image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     * @param  int $limit # Pagination page limit Number of covers per page for paginated results. (optional)
     * @param  int $offset # Pagination page offset Offset for paginated results. (optional, default to 0)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Cover[]
     */
    public function coverTypeGet($type, $id, $format = null, $generic = true, $size = null, $limit = null, $offset = 0)
    {
        list($response) = $this->coverTypeGetWithHttpInfo($type, $id, $format, $generic, $size, $limit, $offset);
        return $response;
    }

    /**
     * Operation coverTypeGetWithHttpInfo
     *
     * Search covers
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string[] $id # ID A list of IDs. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list of image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     * @param  int $limit # Pagination page limit Number of covers per page for paginated results. (optional)
     * @param  int $offset # Pagination page offset Offset for paginated results. (optional, default to 0)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Cover[], HTTP status code, HTTP response headers (array of strings)
     */
    public function coverTypeGetWithHttpInfo($type, $id, $format = null, $generic = true, $size = null, $limit = null, $offset = 0)
    {
        $request = $this->coverTypeGetRequest($type, $id, $format, $generic, $size, $limit, $offset);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Cover[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Cover[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Cover[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Cover[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation coverTypeGetAsync
     *
     * Search covers
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string[] $id # ID A list of IDs. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list of image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     * @param  int $limit # Pagination page limit Number of covers per page for paginated results. (optional)
     * @param  int $offset # Pagination page offset Offset for paginated results. (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function coverTypeGetAsync($type, $id, $format = null, $generic = true, $size = null, $limit = null, $offset = 0)
    {
        return $this->coverTypeGetAsyncWithHttpInfo($type, $id, $format, $generic, $size, $limit, $offset)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation coverTypeGetAsyncWithHttpInfo
     *
     * Search covers
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string[] $id # ID A list of IDs. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list of image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     * @param  int $limit # Pagination page limit Number of covers per page for paginated results. (optional)
     * @param  int $offset # Pagination page offset Offset for paginated results. (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function coverTypeGetAsyncWithHttpInfo($type, $id, $format = null, $generic = true, $size = null, $limit = null, $offset = 0)
    {
        $returnType = '\OpenAPI\Client\Model\Cover[]';
        $request = $this->coverTypeGetRequest($type, $id, $format, $generic, $size, $limit, $offset);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'coverTypeGet'
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string[] $id # ID A list of IDs. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list of image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     * @param  int $limit # Pagination page limit Number of covers per page for paginated results. (optional)
     * @param  int $offset # Pagination page offset Offset for paginated results. (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function coverTypeGetRequest($type, $id, $format = null, $generic = true, $size = null, $limit = null, $offset = 0)
    {
        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling coverTypeGet'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling coverTypeGet'
            );
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling DefaultApi.coverTypeGet, must be bigger than or equal to 1.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling DefaultApi.coverTypeGet, must be bigger than or equal to 0.');
        }


        $resourcePath = '/cover/{type}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($id)) {
            $id = ObjectSerializer::serializeCollection($id, 'csv', true);
        }
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id);
        }
        // query params
        if (is_array($format)) {
            $format = ObjectSerializer::serializeCollection($format, 'csv', true);
        }
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }
        // query params
        if ($generic !== null) {
            $queryParams['generic'] = ObjectSerializer::toQueryValue($generic);
        }
        // query params
        if (is_array($size)) {
            $size = ObjectSerializer::serializeCollection($size, 'csv', true);
        }
        if ($size !== null) {
            $queryParams['size'] = ObjectSerializer::toQueryValue($size);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }

        // path params
        if ($type !== null) {
            $resourcePath = str_replace(
                '{' . 'type' . '}',
                ObjectSerializer::toPathValue($type),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation coverTypeIdGet
     *
     * Get cover
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string $id # ID The ID of the cover. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list if image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Cover
     */
    public function coverTypeIdGet($type, $id, $format = null, $generic = true, $size = null)
    {
        list($response) = $this->coverTypeIdGetWithHttpInfo($type, $id, $format, $generic, $size);
        return $response;
    }

    /**
     * Operation coverTypeIdGetWithHttpInfo
     *
     * Get cover
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string $id # ID The ID of the cover. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list if image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Cover, HTTP status code, HTTP response headers (array of strings)
     */
    public function coverTypeIdGetWithHttpInfo($type, $id, $format = null, $generic = true, $size = null)
    {
        $request = $this->coverTypeIdGetRequest($type, $id, $format, $generic, $size);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Cover' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Cover', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Cover';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Cover',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation coverTypeIdGetAsync
     *
     * Get cover
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string $id # ID The ID of the cover. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list if image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function coverTypeIdGetAsync($type, $id, $format = null, $generic = true, $size = null)
    {
        return $this->coverTypeIdGetAsyncWithHttpInfo($type, $id, $format, $generic, $size)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation coverTypeIdGetAsyncWithHttpInfo
     *
     * Get cover
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string $id # ID The ID of the cover. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list if image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function coverTypeIdGetAsyncWithHttpInfo($type, $id, $format = null, $generic = true, $size = null)
    {
        $returnType = '\OpenAPI\Client\Model\Cover';
        $request = $this->coverTypeIdGetRequest($type, $id, $format, $generic, $size);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'coverTypeIdGet'
     *
     * @param  \OpenAPI\Client\Model\Type $type # ID type The type of the ID, i.e. \&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;, or \&quot;issn-vol-nr\&quot;. (required)
     * @param  string $id # ID The ID of the cover. (required)
     * @param  string[] $format # Formats A list of image formats you want to receive the cover(s) in. (optional)
     * @param  bool $generic # Generic covers If we should include generic front page covers or not for ressources without a cover. (optional, default to true)
     * @param  string[] $size # Image sizes A list if image sizes (Cloudinary transformations) for the cover(s) you want to receive. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function coverTypeIdGetRequest($type, $id, $format = null, $generic = true, $size = null)
    {
        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling coverTypeIdGet'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling coverTypeIdGet'
            );
        }

        $resourcePath = '/cover/{type}/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($format)) {
            $format = ObjectSerializer::serializeCollection($format, 'csv', true);
        }
        if ($format !== null) {
            $queryParams['format'] = ObjectSerializer::toQueryValue($format);
        }
        // query params
        if ($generic !== null) {
            $queryParams['generic'] = ObjectSerializer::toQueryValue($generic);
        }
        // query params
        if (is_array($size)) {
            $size = ObjectSerializer::serializeCollection($size, 'csv', true);
        }
        if ($size !== null) {
            $queryParams['size'] = ObjectSerializer::toQueryValue($size);
        }

        // path params
        if ($type !== null) {
            $resourcePath = str_replace(
                '{' . 'type' . '}',
                ObjectSerializer::toPathValue($type),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
