tools:
  php_code_sniffer:
    config:
      standard: Drupal
    extensions:
      - module
      - inc
      - install
      - test
      - profile
      - theme
  js_hint:
    use_native_config: true

build_failure_conditions:
  # No new issues allowed.
  - 'issues.new.exists'

filter:
    excluded_paths:
        # Generated Features code
        - '*.features.*'
        - '*.feeds_importer_default.inc'
        - '*.field_group.inc'
        - '*.layouts.inc'
        - '*.pages_default.inc'
        - '*.panels_default.inc'
        - '*.panelizer.inc'
        - '*.relation_type_default.inc'
        - '*.strongarm.inc'
        - '*.views_default.inc'
        # Generated webservice client code for FBS
        - modules/fbs/prancer/*
        # Third party dependencies for FBS
        - modules/fbs/vendor/*
        # Third party JavaScript libraries
        - themes/ddbasic/scripts/contrib/*
        # Minified JavaScript files
        - themes/ddbasic/scripts/*.min.js
