tools:
  php_code_sniffer:
    config:
      standard: Drupal
    extensions:
      - module
      - inc
      - install
      - test
      - profile
      - theme
  js_hint:
    use_native_config: true

build_failure_conditions:
  # No new issues allowed.
  - 'issues.new.exists'

filter:
    excluded_paths:
        # Generated Features code
        - '*.features.*'
        - '*.feeds_importer_default.inc'
        - '*.field_group.inc'
        - '*.layouts.inc'
        - '*.pages_default.inc'
        - '*.panels_default.inc'
        - '*.panelizer.inc'
        - '*.strongarm.inc'
        - '*.views_default.inc'
        # Generated webservice client code for FBS
        - modules/fbs/prancer/*
        # Third party dependencies for FBS
        - modules/fbs/vendor/*
        # Third party JavaScript libraries
        - themes/ddbasic/scripts/contrib/*
        # Minified JavaScript files
        - themes/ddbasic/scripts/*min.js
        # Third party JavaScript libraries used in modules
        - modules/ding_webtrends/js/webtrends*.js
        - modules/ting_search_carousel/js/jquery.*
        - modules/contrib/jquery_update/replace/ui/external/jquery.cookie*.js
        - modules/ding_facetbrowser/js/jquery.cookie*.js
        - modules/ding_toggle_format/js/jquery.cookie*.js
        - modules/ding_tabroll/js/jquery-ui-tabs-rotate*.js
