<?php

// Target browser. By default, tests were created under firefox.
define('TARGET_BROWSER', '*firefox');
// Target URL. Which site to run tests on.
define('TARGET_URL', 'http://ding2tal.easyting.dk');
// Site locale. By default, tests were created under EN language.
define('TARGET_URL_LANG', 'en');
// Test user credentials.
define('TARGET_URL_USER', '1111110022');
define('TARGET_URL_USER_PASS', '5555');
