<?php

/**
 * Implements hook_block_info()
 */
function ding_facetbrowser_block_info() {
  $blocks['facetbrowser'] = array(
    'info'  => t('Facet browser'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 *
 * @return Array
 */
function ding_facetbrowser_block_view($delta = FALSE) {
  drupal_add_js(drupal_get_path('module', 'ding_facetbrowser') . '/facetbrowser.js');
  $block = array();

  $search_results = module_invoke_all('ding_facetbrowser');
  if (count($search_results) == FALSE) {
    return $block;
  }
  switch ($delta) {
    case 'facetbrowser':
      $block['subject'] = t('Facet browser');
      $block['content'] = _build_facetsbrowser($search_results);
    break;
  }

  return $block;
}

/**
 * Bulid the facetbrowser as an item_list
 *
 * @param $all_facets Array
 * @return String
 */
function _build_facetsbrowser($all_facets = FALSE) {
  $output   = FALSE;
  if (is_array($all_facets)) {
    foreach ($all_facets as $facet_type) {
      $elements = array();
      $title = $facet_type->name;
      if (count($facet_type->terms) == TRUE) {
        foreach ($facet_type->terms as $facet_name => $facet_count) {
          $elements[] = strtr('%name', array(
            '%name'  => $facet_name,
            '%count' => $facet_count,
          )) ;
        }
        $output .= theme('item_list', array(
          'type'       => 'ul',
          'attributes' => array('id' => $facet_type->name),
          'title'      => $facet_type->name,
          'items'      => $elements,
        ));
      }
    }
  }
  return $output;
}

/**
 * Implements hook_ding_facetbrowser() from the apachesolr_search module
 * to prevent from hacking in contrib module.
 */
function apachesolr_search_ding_facetbrowser() {
  $facets = $facet_terms = array();
  $fields = array(
    1 => 'tags',
    2 => 'category',
  );

  if (apachesolr_has_searched()) {
    $results = _apachesolr_static_result();
    foreach ($results as $result) {
      $node = node_load($result->nid);
      if ($node instanceof stdClass) {
        foreach ($fields as $vocab_id => $vocab_name) {
          $field_name = 'field_' . $vocab_name;
          if (is_array($node->$field_name) && count($node->$field_name) == TRUE) {
            foreach ($node->$field_name as $taxonomy) {
              if (is_array($taxonomy)) {
                foreach ($taxonomy as $term) {
                  $term_data = taxonomy_term_load_multiple(array($term['tid']));
                  $facet_terms[$vocab_name][$term_data[$term['tid']]->name] = $term_data[$term['tid']]->name;
                }
                $facets[$vocab_name] = (object)array(
                  'name' => $field_name,
                  'terms' => $facet_terms[$vocab_name],
                );
              }
            }
          }
        }
      }
    }
  }
  return $facets;
}

/**
 * Implements hook_apachesolr_search_result_alter().
 *
 * Save the search result in a static variable to be able to use it in blocks and so on.
 */
function ding_facetbrowser_apachesolr_search_result_alter(&$doc) {
  _apachesolr_static_result($doc);
}

/*
 * Save the search result as in static variable
 */
function _apachesolr_static_result($result = FALSE) {
  static $search_result = array();
  if ($result instanceof stdClass) {
    $search_result[] = $result;
  }
  return $search_result;
}
