<?php
/**
 * @file
 * Code for the Ding event feature.
 */

/**
 * Implements hook_ding_library_menu_links().
 */
function ding_event_ding_library_menu_links($node) {
  $links = array();

  if (!empty($node->group_group[LANGUAGE_NONE][0]['value']) || !empty($node->group_group[$node->language][0]['value'])) {
    $links['events'] = array(
      'title' => t('Events'),
      'url_prefix' => 'events',
    );
  }

  return $links;
}

include_once('ding_event.features.inc');

