<?php
/**
 * @file
 * Code for the Ding User Frontend feature.
 */

/**
 * Implements hook_preprocess_page().
 */
function ding_user_frontend_preprocess_page(&$variables) {
  // unset tabs in pages with panels that also has tabs.
  if (in_array('page__user', $variables['theme_hook_suggestions'])) {
    unset($variables['tabs']['#primary']);
    unset($variables['tabs']['#secondary']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove locale form fields, if available.
 */
function ding_user_frontend_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['locale'])) {
    unset($form['locale']);
  }
}


/**
 * Implements hook_block_info().
 */
function ding_user_frontend_block_info() {
  $blocks = array();

  $blocks['ding-username'] = array(
    'info' => t('Ding user name'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['ding-user-loan-number'] = array(
    'info' => t('Ding loan, reservation, and debt count'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ding_user_frontend_block_view($delta = '') {
  $block = array();
  global $user;

  switch ($delta) {
    case 'ding-username':
      if ($user->uid > 0) {
        $name = (!empty($user->data['display_name'])) ? $user->data['display_name'] : $user->name;

        if (!empty($name)) {
          $block['content'] = theme('ding_user_frontend_user_name', array(
            'account' => $user,
            'name' => $name,
          ));
        }
      }
      break;
    case 'ding-user-loan-number':
      try {
        // We don't really need the credentials here, but getting them
        // causes an exception to be thrown if user is not
        // authenticated, exiting this block of code, which is what we
        // want. No credentials, no user status.
        ding_user_get_creds($user);

        $block['content'] = theme('ding_user_frontend_user_status', array(
          'loan_count' => count(ding_provider_invoke_page('loan', 'list', $user)),
          'reservation_count' => count(ding_provider_invoke_page('reservation', 'list', $user)),
          'debt_count' => count(ding_provider_invoke_page('debt', 'list', $user)),
        ));
      } catch ( Exception $e ) { return; }

      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function ding_user_frontend_theme($existing, $type, $theme, $path) {
  return array(
    'ding_user_frontend_user_name' => array(
      'variables' => array('account' => NULL, 'name' => NULL),
      'template' => 'ding_user_frontend_user_name',
      'path' => $path . '/templates',
    ),
    'ding_user_frontend_user_status' => array(
      'variables' => array('loan_count' => NULL, 'reservation_count' => NULL, 'debt_count' => NULL),
      'template' => 'ding_user_frontend_user_status',
      'path' => $path . '/templates',
    ),
  );
}

include_once('ding_user_frontend.features.inc');

