<?php

/**
 * @file
 * Various integration with panels to create panel panes and more.
 */

/** 
 * Implements hook_ctools_plugin_directory -
 * This lets ctools know to scan my module for a content_type plugin file
 * Detailed docks in ctools/ctools.api.php 
 */ 
function ding_content_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_enable().
 *
 * Create taxonomy vocabolary if needed.
 */
function ding_content_enable() {
  if (!taxonomy_vocabulary_machine_name_load('ding_content_tags')) {
    $vocabulary = (object) array(
      'name' => t('Tags'),
      'machine_name' => 'ding_content_tags',
      'module' => 'ding_content',
    );
    taxonomy_vocabulary_save($vocabulary);
  }
}
