; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[ding_content][type] = "module"
projects[ding_content][download][type] = "git"
projects[ding_content][download][url] = "git@github.com:ding2tal/ding_content.git"
projects[ding_content][download][branch] = "development"

projects[ding_page][type] = "module"
projects[ding_page][download][type] = "git"
projects[ding_page][download][url] = "git@github.com:ding2tal/ding_page.git"
projects[ding_page][download][branch] = "development"

projects[ding_user_roles][type] = "module"
projects[ding_user_roles][download][type] = "git"
projects[ding_user_roles][download][url] = "git@github.com:ding2tal/ding_user_roles.git"
projects[ding_user_roles][download][branch] = "development"

projects[ting_reference][type] = "module"
projects[ting_reference][download][type] = "git"
projects[ting_reference][download][url] = "git@github.com:ding2tal/ting_reference.git"
projects[ting_reference][download][branch] = "development"

projects[cache_actions][subdir] = "contrib"
projects[cache_actions][version] = "2.0-alpha5"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"
projects[ctools][patch][0] = "http://drupal.org/files/ctools-n1925018-12.patch"

projects[cs_adaptive_image][subdir] = "contrib"
projects[cs_adaptive_image][version] = "1.0"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-beta2"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-unstable7"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-unstable7"

projects[og][type] = "module"
projects[og][subdir] = "contrib"
projects[og][download][type] = "git"
projects[og][download][url] = "http://git.drupal.org/project/og.git"
projects[og][download][tag] = "7.x-1.3"
projects[og][patch][0] = "http://drupal.org/files/1320778.patch"

projects[similarterms][type] = "module"
projects[similarterms][subdir] = "contrib"
projects[similarterms][download][type] = "git"
projects[similarterms][download][url] = "http://git.drupal.org/project/similarterms.git"
projects[similarterms][download][revision] = "d0f10f5fdcb3a16855cff93094c4139a32e585f6"
projects[similarterms][patch][0] = "https://raw.github.com/ding2/patches/master/similarterms-combined-patches.patch"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

