<?php

include_once('ding_tabroll.features.inc');

/**
 * Implements hook_theme().
 *
 * See http://views-help.doc.logrus.com/help/views/api-default-views for help with providing default .tpl files for your views
 */
function ding_tabroll_theme($existing) {
  $path = drupal_get_path('module', 'ding_tabroll') . '/templates';
  return array(
    'views_view_unformatted__tabroll' => array (
      'arguments' => array('view' => NULL, 'options' => NULL, 'rows' => NULL, 'title' => NULL),
      'template' => 'views-view-unformatted--tabroll',
      'original hook' => 'views_view_unformatted',
      'path' => $path,
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view_unformatted',
        'ding_tabroll_preprocess_views_view_unformatted__tabroll',
      ),
    ),
    'views_view_fields__tabroll' => array (
      'arguments' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'template' => 'views-view-fields--tabroll',
      'original hook' => 'views_view_fields',
      'path' => $path,
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view_fields',
        'ding_tabroll_preprocess_views_view_fields__tabroll',
      ),
    ),
  );
}

/**
 * Implements hook_init().
 */
function ding_tabroll_init() {
  // Add default CSS and JavaScript
  drupal_add_js(drupal_get_path('module', 'ding_tabroll') . '/js/ding_tabroll.js');
  drupal_add_css(drupal_get_path('module', 'ding_tabroll') . '/css/ding_tabroll.css');
}

/**
 * Implements hook_views_pre_render().
 */
function ding_tabroll_views_pre_render(&$view) {
  // HACK / kasperg: Reset the view title. For some reason it is set to "Queue"
  // but I cannot determine why/where. As the pre-nodequeue view had no title
  // we remove the title by force.
  // Site developers may want to set the title for their own views using the
  // panel pane which supports title overrride.
  if ($view->name == 'tabroll') {
    $view->build_info['title'] = '';
  }
}
