; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta3"

projects[cache_actions][subdir] = "contrib"
projects[cache_actions][version] = "2.0-alpha5"

projects[cs_adaptive_image][subdir] = "contrib"
projects[cs_adaptive_image][version] = "1.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"
projects[ctools][patch][0] = "http://drupal.org/files/ctools-n1925018-12.patch"

projects[email][subdir] = "contrib"
projects[email][version] = "1.2"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[geocoder][subdir] = "contrib"
projects[geocoder][version] = "1.2"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "1.1"

projects[nodequeue][subdir] = "contrib"
projects[nodequeue][version] = "2.0-beta1"

projects[proj4js][subdir] = "contrib"
projects[proj4js][version] = "1.2"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-unstable7"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-unstable7"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3"

projects[og][type] = "module"
projects[og][subdir] = "contrib"
projects[og][download][type] = "git"
projects[og][download][url] = "http://git.drupal.org/project/og.git"
projects[og][download][tag] = "7.x-1.3"
projects[og][patch][0] = "http://drupal.org/files/1320778.patch"

projects[openlayers][subdir] = "contrib"
projects[openlayers][version] = "2.0-beta5"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[tipsy][subdir] = "contrib"
projects[tipsy][version] = "1.0-rc1"

projects[opening_hours][subdir] = "contrib"
projects[opening_hours][version] = "1.4-beta1"

; Libraries
libraries[openlayers][download][type] = "get"
libraries[openlayers][download][url] = "http://openlayers.org/download/OpenLayers-2.12.tar.gz"

libraries[openlayers_themes][download][type] = "git"
libraries[openlayers_themes][download][url] = "git@github.com:developmentseed/openlayers_themes.git"

