<?php
/**
 * @file
 * Create news content type and displays.
 */

/**
 * Implements hook_enable().
 *
 * Create taxonomy vocabolary if needed.
 */
function ding_news_enable() {
  if (!taxonomy_vocabulary_machine_name_load('ding_news')) {
    $vocabulary = (object) array(
      'name' => t('News category'),
      'machine_name' => 'ding_news',
      'module' => 'ding_news',
    );
    taxonomy_vocabulary_save($vocabulary);
  }
}

/**
 * Implements hook_ding_library_menu_links().
 */
function ding_news_ding_library_menu_links($node) {
  $links = array();

  if (!empty($node->group_group[$node->language][0]['value'])) {
    $links['news'] = array(
      'title' => t('News'),
      'url_prefix' => 'news',
    );
  }

  return $links;
}

include_once('ding_news.features.inc');

