core = 7.x
api = 2

; Include ding2 make file
includes[ding2] = "project.make"

; easyOPAC modules
projects[bibdk_subject_hierarchy][type]             = "module"
projects[bibdk_subject_hierarchy][subdir]           = ""
projects[bibdk_subject_hierarchy][download][type]   = "git"
projects[bibdk_subject_hierarchy][download][url]    = "git@github.com:easySuite/bibdk_subject_hierarchy.git"
;projects[bibdk_subject_hierarchy][download][tag]    = ""
projects[bibdk_subject_hierarchy][download][branch] = "development"

projects[bibliofil_lists][type]             = "module"
projects[bibliofil_lists][subdir]           = ""
projects[bibliofil_lists][download][type]   = "git"
projects[bibliofil_lists][download][url]    = "git@github.com:easySuite/bibliofil_lists.git"
;projects[bibliofil_lists][download][tag]    = ""
projects[bibliofil_lists][download][branch] = "development"

projects[ding_billetexpressen_import][type]             = "module"
projects[ding_billetexpressen_import][subdir]           = ""
projects[ding_billetexpressen_import][download][type]   = "git"
projects[ding_billetexpressen_import][download][url]    = "git@github.com:easySuite/ding_billetexpressen_import.git"
;projects[ding_billetexpressen_import][download][tag]    = ""
projects[ding_billetexpressen_import][download][branch] = "development"

projects[ding_billettendk_import][type]             = "module"
projects[ding_billettendk_import][subdir]           = ""
projects[ding_billettendk_import][download][type]   = "git"
projects[ding_billettendk_import][download][url]    = "git@github.com:easySuite/ding_billettendk_import.git"
;projects[ding_billettendk_import][download][tag]    = ""
projects[ding_billettendk_import][download][branch] = "development"

projects[ding_bibliotek_info][type]             = "module"
projects[ding_bibliotek_info][subdir]           = ""
projects[ding_bibliotek_info][download][type]   = "git"
projects[ding_bibliotek_info][download][url]    = "git@github.com:easySuite/ding_bibliotek_info.git"
;projects[ding_bibliotek_info][download][tag]    = ""
projects[ding_bibliotek_info][download][branch] = "development"

projects[ding_blog][type]             = "module"
projects[ding_blog][subdir]           = ""
projects[ding_blog][download][type]   = "git"
projects[ding_blog][download][url]    = "git@github.com:easySuite/ding_blog.git"
;projects[ding_blog][download][tag]    = ""
projects[ding_blog][download][branch] = "development"

projects[ding_calendar][type]             = "module"
projects[ding_calendar][subdir]           = ""
projects[ding_calendar][download][type]   = "git"
projects[ding_calendar][download][url]    = "git@github.com:easySuite/ding_calendar.git"
;projects[ding_calendar][download][tag]    = ""
projects[ding_calendar][download][branch] = "development"

projects[ding_campaign_plus_extra][type]             = "module"
projects[ding_campaign_plus_extra][subdir]           = ""
projects[ding_campaign_plus_extra][download][type]   = "git"
projects[ding_campaign_plus_extra][download][url]    = "git@github.com:easySuite/ding_campaign_plus_extra.git"
;projects[ding_campaign_plus_extra][download][tag]    = ""
projects[ding_campaign_plus_extra][download][branch] = "development"

projects[ding_campaign_mobile][type]             = "module"
projects[ding_campaign_mobile][subdir]           = ""
projects[ding_campaign_mobile][download][type]   = "git"
projects[ding_campaign_mobile][download][url]    = "git@github.com:easySuite/ding_campaign_mobile.git"
;projects[ding_campaign_mobile][download][tag]    = ""
projects[ding_campaign_mobile][download][branch] = "development"

projects[ding_collection_reservation][type]             = "module"
projects[ding_collection_reservation][subdir]           = ""
projects[ding_collection_reservation][download][type]   = "git"
projects[ding_collection_reservation][download][url]    = "git@github.com:easySuite/ding_collection_reservation.git"
;projects[ding_collection_reservation][download][tag]    = ""
projects[ding_collection_reservation][download][branch] = "development"

projects[ding_context_search][type]             = "module"
projects[ding_context_search][subdir]           = ""
projects[ding_context_search][download][type]   = "git"
projects[ding_context_search][download][url]    = "git@github.com:easySuite/ding_context_search.git"
;projects[ding_context_search][download][tag]    = ""
projects[ding_context_search][download][branch] = "development"

projects[ding_custom_facets][type]             = "module"
projects[ding_custom_facets][subdir]           = ""
projects[ding_custom_facets][download][type]   = "git"
projects[ding_custom_facets][download][url]    = "git@github.com:easySuite/ding_custom_facets.git"
;projects[ding_custom_facets][download][tag]    = ""
projects[ding_custom_facets][download][branch] = "development"

projects[ding_easyscreen_teaser][type]             = "module"
projects[ding_easyscreen_teaser][subdir]           = ""
projects[ding_easyscreen_teaser][download][type]   = "git"
projects[ding_easyscreen_teaser][download][url]    = "git@github.com:easySuite/ding_easyscreen_teaser.git"
;projects[ding_easyscreen_teaser][download][tag]    = ""
projects[ding_easyscreen_teaser][download][branch] = "development"

projects[ding_event_calendar][type]             = "module"
projects[ding_event_calendar][subdir]           = ""
projects[ding_event_calendar][download][type]   = "git"
projects[ding_event_calendar][download][url]    = "git@github.com:easySuite/ding_event_calendar.git"
;projects[ding_event_calendar][download][tag]    = ""
projects[ding_event_calendar][download][branch] = "development"

projects[ding_event_clone][type]             = "module"
projects[ding_event_clone][subdir]           = ""
projects[ding_event_clone][download][type]   = "git"
projects[ding_event_clone][download][url]    = "git@github.com:easySuite/ding_event_clone.git"
;projects[ding_event_clone][download][tag]    = ""
projects[ding_event_clone][download][branch] = "development"

projects[ding_event_subscriptions][type]             = "module"
projects[ding_event_subscriptions][subdir]           = ""
projects[ding_event_subscriptions][download][type]   = "git"
projects[ding_event_subscriptions][download][url]    = "git@github.com:easySuite/ding_event_subscriptions.git"
;projects[ding_event_subscriptions][download][tag]    = ""
projects[ding_event_subscriptions][download][branch] = "development"

projects[ding_header_opening_hours][type]             = "module"
projects[ding_header_opening_hours][subdir]           = ""
projects[ding_header_opening_hours][download][type]   = "git"
projects[ding_header_opening_hours][download][url]    = "git@github.com:easySuite/ding_header_opening_hours.git"
;projects[ding_header_opening_hours][download][tag]    = ""
projects[ding_header_opening_hours][download][branch] = "development"

projects[ding_history_back][type]             = "module"
projects[ding_history_back][subdir]           = ""
projects[ding_history_back][download][type]   = "git"
projects[ding_history_back][download][url]    = "git@github.com:easySuite/ding_history_back.git"
;projects[ding_history_back][download][tag]    = ""
projects[ding_history_back][download][branch] = "development"

projects[ding_holdings_highlight][type]             = "module"
projects[ding_holdings_highlight][subdir]           = ""
projects[ding_holdings_highlight][download][type]   = "git"
projects[ding_holdings_highlight][download][url]    = "git@github.com:easySuite/ding_holdings_highlight.git"
;projects[ding_holdings_highlight][download][tag]    = ""
projects[ding_holdings_highlight][download][branch] = "development"

projects[ding_item_list][type]             = "module"
projects[ding_item_list][subdir]           = ""
projects[ding_item_list][download][type]   = "git"
projects[ding_item_list][download][url]    = "git@github.com:easySuite/ding_item_list.git"
;projects[ding_item_list][download][tag]    = ""
projects[ding_item_list][download][branch] = "development"

projects[ding_kultunaut_import][type]             = "module"
projects[ding_kultunaut_import][subdir]           = ""
projects[ding_kultunaut_import][download][type]   = "git"
projects[ding_kultunaut_import][download][url]    = "git@github.com:easySuite/ding_kultunaut_import.git"
;projects[ding_kultunaut_import][download][tag]    = ""
projects[ding_kultunaut_import][download][branch] = "development"

projects[ding_language][type]             = "module"
projects[ding_language][subdir]           = ""
projects[ding_language][download][type]   = "git"
projects[ding_language][download][url]    = "git@github.com:easySuite/ding_language.git"
;projects[ding_language][download][tag]    = ""
projects[ding_language][download][branch] = "development"

projects[ding_library_opening_hours][type]             = "module"
projects[ding_library_opening_hours][subdir]           = ""
projects[ding_library_opening_hours][download][type]   = "git"
projects[ding_library_opening_hours][download][url]    = "git@github.com:easySuite/ding_library_opening_hours.git"
;projects[ding_library_opening_hours][download][tag]    = ""
projects[ding_library_opening_hours][download][branch] = "development"

projects[ding_menu_alt][type]             = "module"
projects[ding_menu_alt][subdir]           = ""
projects[ding_menu_alt][download][type]   = "git"
projects[ding_menu_alt][download][url]    = "git@github.com:easySuite/ding_menu_alt.git"
;projects[ding_menu_alt][download][tag]    = ""
projects[ding_menu_alt][download][branch] = "development"

projects[ding_more_info][type]             = "module"
projects[ding_more_info][subdir]           = ""
projects[ding_more_info][download][type]   = "git"
projects[ding_more_info][download][url]    = "git@github.com:easySuite/ding_more_info.git"
;projects[ding_more_info][download][tag]    = ""
projects[ding_more_info][download][branch] = "development"

projects[ding_nis][type]             = "module"
projects[ding_nis][subdir]           = ""
projects[ding_nis][download][type]   = "git"
projects[ding_nis][download][url]    = "git@github.com:easySuite/ding_nis.git"
;projects[ding_nis][download][tag]    = ""
projects[ding_nis][download][branch] = "development"

projects[ding_node_search_autocomplete][type]             = "module"
projects[ding_node_search_autocomplete][subdir]           = ""
projects[ding_node_search_autocomplete][download][type]   = "git"
projects[ding_node_search_autocomplete][download][url]    = "git@github.com:easySuite/ding_node_search_autocomplete.git"
;projects[ding_node_search_autocomplete][download][tag]    = ""
projects[ding_node_search_autocomplete][download][branch] = "development"

projects[ding_print_button][type]             = "module"
projects[ding_print_button][subdir]           = ""
projects[ding_print_button][download][type]   = "git"
projects[ding_print_button][download][url]    = "git@github.com:easySuite/ding_print_button.git"
;projects[ding_print_button][download][tag]    = ""
projects[ding_print_button][download][branch] = "development"

projects[ding_readers_compass][type]             = "module"
projects[ding_readers_compass][subdir]           = ""
projects[ding_readers_compass][download][type]   = "git"
projects[ding_readers_compass][download][url]    = "git@github.com:easySuite/ding_readers_compass.git"
;projects[ding_readers_compass][download][tag]    = ""
projects[ding_readers_compass][download][branch] = "development"

projects[ding_reading_club][type]             = "module"
projects[ding_reading_club][subdir]           = ""
projects[ding_reading_club][download][type]   = "git"
projects[ding_reading_club][download][url]    = "git@github.com:easySuite/ding_reading_club.git"
;projects[ding_reading_club][download][tag]    = ""
projects[ding_reading_club][download][branch] = "development"

projects[ding_related_content_search][type]             = "module"
projects[ding_related_content_search][subdir]           = ""
projects[ding_related_content_search][download][type]   = "git"
projects[ding_related_content_search][download][url]    = "git@github.com:easySuite/ding_related_content_search.git"
;projects[ding_related_content_search][download][tag]    = ""
projects[ding_related_content_search][download][branch] = "development"

projects[ding_reservation_settings][type]             = "module"
projects[ding_reservation_settings][subdir]           = ""
projects[ding_reservation_settings][download][type]   = "git"
projects[ding_reservation_settings][download][url]    = "git@github.com:easySuite/ding_reservation_settings.git"
;projects[ding_reservation_settings][download][tag]    = ""
projects[ding_reservation_settings][download][branch] = "development"

projects[ding_search_collection][type]             = "module"
projects[ding_search_collection][subdir]           = ""
projects[ding_search_collection][download][type]   = "git"
projects[ding_search_collection][download][url]    = "git@github.com:easySuite/ding_search_collection.git"
;projects[ding_search_collection][download][tag]    = ""
projects[ding_search_collection][download][branch] = "development"

projects[ding_social][type]             = "module"
projects[ding_social][subdir]           = ""
projects[ding_social][download][type]   = "git"
projects[ding_social][download][url]    = "git@github.com:easySuite/ding_social.git"
;projects[ding_social][download][tag]    = ""
projects[ding_social][download][branch] = "development"

projects[ding_ting_type_search][type]             = "module"
projects[ding_ting_type_search][subdir]           = ""
projects[ding_ting_type_search][download][type]   = "git"
projects[ding_ting_type_search][download][url]    = "git@github.com:easySuite/ding_ting_type_search.git"
;projects[ding_ting_type_search][download][tag]    = ""
projects[ding_ting_type_search][download][branch] = "development"

projects[ding_user_profile][type]             = "module"
projects[ding_user_profile][subdir]           = ""
projects[ding_user_profile][download][type]   = "git"
projects[ding_user_profile][download][url]    = "git@github.com:easySuite/ding_user_profile.git"
;projects[ding_user_profile][download][tag]    = ""
projects[ding_user_profile][download][branch] = "development"

projects[ding_video][type]             = "module"
projects[ding_video][subdir]           = ""
projects[ding_video][download][type]   = "git"
projects[ding_video][download][url]    = "git@github.com:easySuite/ding_video.git"
;projects[ding_video][download][tag]    = ""
projects[ding_video][download][branch] = "development"

projects[easyddb_facebookshare][type]             = "module"
projects[easyddb_facebookshare][subdir]           = ""
projects[easyddb_facebookshare][download][type]   = "git"
projects[easyddb_facebookshare][download][url]    = "git@github.com:easySuite/easyddb_facebookshare.git"
;projects[easyddb_facebookshare][download][tag]    = ""
projects[easyddb_facebookshare][download][branch] = "development"

projects[easyddb_ee_import][type]             = "module"
projects[easyddb_ee_import][subdir]           = ""
projects[easyddb_ee_import][download][type]   = "git"
projects[easyddb_ee_import][download][url]    = "git@github.com:easySuite/easyddb_ee_import.git"
;projects[easyddb_ee_import][download][tag]    = ""
projects[easyddb_ee_import][download][branch] = "development"

projects[easyddb_dams][type]             = "module"
projects[easyddb_dams][subdir]           = ""
projects[easyddb_dams][download][type]   = "git"
projects[easyddb_dams][download][url]    = "git@github.com:easySuite/easyddb_dams.git"
;projects[easyddb_dams][download][tag]    = ""
projects[easyddb_dams][download][branch] = "development"

projects[easyddb_direct_link][type]             = "module"
projects[easyddb_direct_link][subdir]           = ""
projects[easyddb_direct_link][download][type]   = "git"
projects[easyddb_direct_link][download][url]    = "git@github.com:easySuite/easyddb_direct_link.git"
;projects[easyddb_direct_link][download][tag]    = ""
projects[easyddb_direct_link][download][branch] = "development"

projects[easyddb_extlink_settings][type]             = "module"
projects[easyddb_extlink_settings][subdir]           = ""
projects[easyddb_extlink_settings][download][type]   = "git"
projects[easyddb_extlink_settings][download][url]    = "git@github.com:easySuite/easyddb_extlink_settings.git"
;projects[easyddb_extlink_settings][download][tag]    = ""
projects[easyddb_extlink_settings][download][branch] = "development"

projects[easyddb_frontend_layout][type]             = "module"
projects[easyddb_frontend_layout][subdir]           = ""
projects[easyddb_frontend_layout][download][type]   = "git"
projects[easyddb_frontend_layout][download][url]    = "git@github.com:easySuite/easyddb_frontend_layout.git"
;projects[easyddb_frontend_layout][download][tag]    = ""
projects[easyddb_frontend_layout][download][branch] = "development"

projects[easyddb_legend][type]             = "module"
projects[easyddb_legend][subdir]           = ""
projects[easyddb_legend][download][type]   = "git"
projects[easyddb_legend][download][url]    = "git@github.com:easySuite/easyddb_legend.git"
;projects[easyddb_legend][download][tag]    = ""
projects[easyddb_legend][download][branch] = "development"

projects[easyddb_search_holdings][type]             = "module"
projects[easyddb_search_holdings][subdir]           = ""
projects[easyddb_search_holdings][download][type]   = "git"
projects[easyddb_search_holdings][download][url]    = "git@github.com:easySuite/easyddb_search_holdings.git"
;projects[easyddb_search_holdings][download][tag]    = ""
projects[easyddb_search_holdings][download][branch] = "development"

projects[easyddb_search_radios][type]             = "module"
projects[easyddb_search_radios][subdir]           = ""
projects[easyddb_search_radios][download][type]   = "git"
projects[easyddb_search_radios][download][url]    = "git@github.com:easySuite/easyddb_search_radios.git"
;projects[easyddb_search_radios][download][tag]    = ""
projects[easyddb_search_radios][download][branch] = "development"

projects[easyddb_search_result_reservation][type]             = "module"
projects[easyddb_search_result_reservation][subdir]           = ""
projects[easyddb_search_result_reservation][download][type]   = "git"
projects[easyddb_search_result_reservation][download][url]    = "git@github.com:easySuite/easyddb_search_result_reservation.git"
;projects[easyddb_search_result_reservation][download][tag]    = ""
projects[easyddb_search_result_reservation][download][branch] = "development"

projects[easyddb_xml_events][type]             = "module"
projects[easyddb_xml_events][subdir]           = ""
projects[easyddb_xml_events][download][type]   = "git"
projects[easyddb_xml_events][download][url]    = "git@github.com:easySuite/easyddb_xml_events.git"
;projects[easyddb_xml_events][download][tag]    = ""
projects[easyddb_xml_events][download][branch] = "development"

projects[easyddb_wayfinder][type]             = "module"
projects[easyddb_wayfinder][subdir]           = ""
projects[easyddb_wayfinder][download][type]   = "git"
projects[easyddb_wayfinder][download][url]    = "git@github.com:easySuite/easyddb_wayfinder.git"
;projects[easyddb_wayfinder][download][tag]    = ""
projects[easyddb_wayfinder][download][branch] = "development"

projects[easyddb_zerohit_redirect][type]             = "module"
projects[easyddb_zerohit_redirect][subdir]           = ""
projects[easyddb_zerohit_redirect][download][type]   = "git"
projects[easyddb_zerohit_redirect][download][url]    = "git@github.com:easySuite/easyddb_zerohit_redirect.git"
;projects[easyddb_zerohit_redirect][download][tag]    = ""
projects[easyddb_zerohit_redirect][download][branch] = "development"

projects[easyopac_collection_links][type]             = "module"
projects[easyopac_collection_links][subdir]           = ""
projects[easyopac_collection_links][download][type]   = "git"
projects[easyopac_collection_links][download][url]    = "git@github.com:easySuite/easyopac_collection_links.git"
;projects[easyopac_collection_links][download][tag]    = ""
projects[easyopac_collection_links][download][branch] = "development"

projects[easyopac_external_videos][type]             = "module"
projects[easyopac_external_videos][subdir]           = ""
projects[easyopac_external_videos][download][type]   = "git"
projects[easyopac_external_videos][download][url]    = "git@github.com:easySuite/easyopac_external_videos.git"
;projects[easyopac_external_videos][download][tag]    = ""
projects[easyopac_external_videos][download][branch] = "development"

projects[easyopac_abstracts_override][type]             = "module"
projects[easyopac_abstracts_override][subdir]           = ""
projects[easyopac_abstracts_override][download][type]   = "git"
projects[easyopac_abstracts_override][download][url]    = "git@github.com:easySuite/easyopac_abstracts_override.git"
;projects[easyopac_abstracts_override][download][tag]    = ""
projects[easyopac_abstracts_override][download][branch] = "development"

projects[easyddb_event_status][type]             = "module"
projects[easyddb_event_status][subdir]           = ""
projects[easyddb_event_status][download][type]   = "git"
projects[easyddb_event_status][download][url]    = "git@github.com:easySuite/easyddb_event_status.git"
;projects[easyddb_event_status][download][tag]    = ""
projects[easyddb_event_status][download][branch] = "development"

projects[easyopac_facets][type]             = "module"
projects[easyopac_facets][subdir]           = ""
projects[easyopac_facets][download][type]   = "git"
projects[easyopac_facets][download][url]    = "git@github.com:easySuite/easyopac_facets.git"
;projects[easyopac_facets][download][tag]    = ""
projects[easyopac_facets][download][branch] = "development"

projects[easyopac_facets_translate][type]             = "module"
projects[easyopac_facets_translate][subdir]           = ""
projects[easyopac_facets_translate][download][type]   = "git"
projects[easyopac_facets_translate][download][url]    = "git@github.com:easySuite/easyopac_facets_translate.git"
;projects[easyopac_facets_translate][download][tag]    = ""
projects[easyopac_facets_translate][download][branch] = "development"

projects[easyopac_recommender][type]             = "module"
projects[easyopac_recommender][subdir]           = ""
projects[easyopac_recommender][download][type]   = "git"
projects[easyopac_recommender][download][url]    = "git@github.com:easySuite/easyopac_recommender.git"
;projects[easyopac_recommender][download][tag]    = ""
projects[easyopac_recommender][download][branch] = "development"

projects[easyopac_status][type]             = "module"
projects[easyopac_status][subdir]           = ""
projects[easyopac_status][download][type]   = "git"
projects[easyopac_status][download][url]    = "git@github.com:easySuite/easyopac_status.git"
;projects[easyopac_status][download][tag]    = ""
projects[easyopac_status][download][branch] = "development"

projects[emailkanon][type]             = "module"
projects[emailkanon][subdir]           = ""
projects[emailkanon][download][type]   = "git"
projects[emailkanon][download][url]    = "git@github.com:easySuite/emailkanon.git"
;projects[emailkanon][download][branch] = "master"
projects[emailkanon][download][branch] = "development"

projects[kultunaut_events][type]             = "module"
projects[kultunaut_events][subdir]           = ""
projects[kultunaut_events][download][type]   = "git"
projects[kultunaut_events][download][url]    = "git@github.com:easySuite/kultunaut_events.git"
;projects[kultunaut_events][download][tag]    = ""
projects[kultunaut_events][download][branch] = "development"

projects[ting_covers_backside][type]             = "module"
projects[ting_covers_backside][subdir]           = ""
projects[ting_covers_backside][download][type]   = "git"
projects[ting_covers_backside][download][url]    = "git@github.com:easySuite/ting_covers_backside.git"
;projects[ting_covers_backside][download][tag]    = ""
projects[ting_covers_backside][download][branch] = "development"

projects[ting_covers_plus][type]             = "module"
projects[ting_covers_plus][subdir]           = ""
projects[ting_covers_plus][download][type]   = "git"
projects[ting_covers_plus][download][url]    = "git@github.com:easySuite/ting_covers_plus.git"
;projects[ting_covers_plus][download][tag]    = ""
projects[ting_covers_plus][download][branch] = "development"

projects[ting_dk5][type]             = "module"
projects[ting_dk5][subdir]           = ""
projects[ting_dk5][download][type]   = "git"
projects[ting_dk5][download][url]    = "git@github.com:easySuite/ting_dk5.git"
;projects[ting_dk5][download][tag]    = ""
projects[ting_dk5][download][branch] = "development"

projects[ting_extended_search][type]             = "module"
projects[ting_extended_search][subdir]           = ""
projects[ting_extended_search][download][type]   = "git"
projects[ting_extended_search][download][url]    = "git@github.com:easySuite/ting_extended_search.git"
;projects[ting_extended_search][download][tag]    = ""
projects[ting_extended_search][download][branch] = "development"

projects[ting_facet_custom][type]             = "module"
projects[ting_facet_custom][subdir]           = ""
projects[ting_facet_custom][download][type]   = "git"
projects[ting_facet_custom][download][url]    = "git@github.com:easySuite/ting_facet_custom.git"
;projects[ting_facet_custom][download][tag]    = ""
projects[ting_facet_custom][download][branch] = "development"

projects[ting_marc][type]             = "module"
projects[ting_marc][subdir]           = ""
projects[ting_marc][download][type]   = "git"
projects[ting_marc][download][url]    = "git@github.com:easySuite/ting_marc.git"
;projects[ting_marc][download][tag]    = ""
projects[ting_marc][download][branch] = "development"

projects[ting_proposed_searches][type]             = "module"
projects[ting_proposed_searches][subdir]           = ""
projects[ting_proposed_searches][download][type]   = "git"
projects[ting_proposed_searches][download][url]    = "git@github.com:easySuite/ting_proposed_searches.git"
;projects[ting_proposed_searches][download][tag]    = ""
projects[ting_proposed_searches][download][branch] = "development"

projects[ting_recommender][type]              = "module"
projects[ting_recommender][subdir]            = ""
projects[ting_recommender][download][type]    = "git"
projects[ting_recommender][download][url]     = "git@github.com:easySuite/ting_recommender.git"
;projects[ting_recommender][download][tag]     = ""
projects[ting_recommender][download][branch]  = "development"

projects[ting_reference_advanced][type]              = "module"
projects[ting_reference_advanced][subdir]            = ""
projects[ting_reference_advanced][download][type]    = "git"
projects[ting_reference_advanced][download][url]     = "git@github.com:easySuite/ting_reference_advanced.git"
;projects[ting_reference_advanced][download][tag]     = ""
projects[ting_reference_advanced][download][branch]  = "development"

projects[ting_search_terms][type]             = "module"
projects[ting_search_terms][subdir]           = ""
projects[ting_search_terms][download][type]   = "git"
projects[ting_search_terms][download][url]    = "git@github.com:easySuite/ting_search_terms.git"
;projects[ting_search_terms][download][tag]    = ""
projects[ting_search_terms][download][branch] = "development"

projects[ting_search_subject][type]             = "module"
projects[ting_search_subject][subdir]           = ""
projects[ting_search_subject][download][type]   = "git"
projects[ting_search_subject][download][url]    = "git@github.com:easySuite/ting_search_subject.git"
;projects[ting_search_subject][download][tag]    = ""
projects[ting_search_subject][download][branch] = "development"

projects[ting_subjects_override][type]             = "module"
projects[ting_subjects_override][subdir]           = ""
projects[ting_subjects_override][download][type]   = "git"
projects[ting_subjects_override][download][url]    = "git@github.com:easySuite/ting_subjects_override.git"
;projects[ting_subjects_override][download][tag]    = ""
projects[ting_subjects_override][download][branch] = "development"

projects[ting_subsearch_suggestions][type]             = "module"
projects[ting_subsearch_suggestions][subdir]           = ""
projects[ting_subsearch_suggestions][download][type]   = "git"
projects[ting_subsearch_suggestions][download][url]    = "git@github.com:easySuite/ting_subsearch_suggestions.git"
;projects[ting_subsearch_suggestions][download][tag]    = ""
projects[ting_subsearch_suggestions][download][branch] = "development"

projects[ting_subsearch_common][type]             = "module"
projects[ting_subsearch_common][subdir]           = ""
projects[ting_subsearch_common][download][type]   = "git"
projects[ting_subsearch_common][download][url]    = "git@github.com:easySuite/ting_subsearch_common.git"
;projects[ting_subsearch_common][download][tag]    = ""
projects[ting_subsearch_common][download][branch] = "development"

projects[ting_subsearch_secondary][type]             = "module"
projects[ting_subsearch_secondary][subdir]           = ""
projects[ting_subsearch_secondary][download][type]   = "git"
projects[ting_subsearch_secondary][download][url]    = "git@github.com:easySuite/ting_subsearch_secondary.git"
;projects[ting_subsearch_secondary][download][tag]    = ""
projects[ting_subsearch_secondary][download][branch] = "development"

projects[ting_subsearch_translate][type]             = "module"
projects[ting_subsearch_translate][subdir]           = ""
projects[ting_subsearch_translate][download][type]   = "git"
projects[ting_subsearch_translate][download][url]    = "git@github.com:easySuite/ting_subsearch_translate.git"
;projects[ting_subsearch_translate][download][tag]    = ""
projects[ting_subsearch_translate][download][branch] = "development"

projects[ting_titles_decoration][type]             = "module"
projects[ting_titles_decoration][subdir]           = ""
projects[ting_titles_decoration][download][type]   = "git"
projects[ting_titles_decoration][download][url]    = "git@github.com:easySuite/ting_titles_decoration.git"
;projects[ting_titles_decoration][download][tag]    = ""
projects[ting_titles_decoration][download][branch] = "development"

; Social Services modules and libraries
projects[social_services][type]             = "module"
projects[social_services][download][type]   = "git"
projects[social_services][subdir]           = ""
projects[social_services][download][url]    = "git@github.com:easySuite/social_services.git"
projects[social_services][download][branch] = "development"

libraries[SocialServices][download][type]   = "git"
libraries[SocialServices][download][url]    = "git@github.com:inleadmedia/SocialServices.git"
libraries[SocialServices][download][branch] = "development"
libraries[SocialServices][destination]      = "modules/social_services/lib"

; To be removed
projects[ding_uninstall_modules][type]             = "module"
projects[ding_uninstall_modules][download][type]   = "git"
projects[ding_uninstall_modules][subdir]           = ""
projects[ding_uninstall_modules][download][url]    = "git@github.com:easySuite/ding_uninstall_modules.git"
projects[ding_uninstall_modules][download][branch] = "master"

projects[ding_sections_migrate][type]             = "module"
projects[ding_sections_migrate][subdir]           = ""
projects[ding_sections_migrate][download][type]   = "git"
projects[ding_sections_migrate][download][url]    = "git@github.com:easySuite/ding_sections_migrate.git"
;projects[ding_sections_migrate][download][tag]    = ""
projects[ding_sections_migrate][download][branch] = "master"

projects[ding_campaign_migrate][type]             = "module"
projects[ding_campaign_migrate][subdir]           = ""
projects[ding_campaign_migrate][download][type]   = "git"
projects[ding_campaign_migrate][download][url]    = "git@github.com:easySuite/ding_campaign_migrate.git"
;projects[ding_campaign_migrate][download][tag]    = ""
projects[ding_campaign_migrate][download][branch] = "development"

projects[easyddb_search_expand][type]             = "module"
projects[easyddb_search_expand][subdir]           = ""
projects[easyddb_search_expand][download][type]   = "git"
projects[easyddb_search_expand][download][url]    = "git@github.com:easySuite/easyddb_search_expand.git"
;projects[easyddb_search_expand][download][tag]    = ""
projects[easyddb_search_expand][download][branch] = "development"

; Bibliofil
projects[bibliofil-subtheme][type]             = "theme"
projects[bibliofil-subtheme][subdir]           = ""
projects[bibliofil-subtheme][download][type]   = "git"
projects[bibliofil-subtheme][download][url]    = "git@github.com:easySuite/bibliofil-subtheme.git"
;projects[bibliofil-subtheme][download][tag]    = ""
projects[bibliofil-subtheme][download][branch] = "development"

projects[lms][type]             = "module"
projects[lms][subdir]           = ""
projects[lms][download][type]   = "git"
projects[lms][download][url]    = "git@github.com:easySuite/lms.git"
;projects[lms][download][tag]    = ""
projects[lms][download][branch] = "development"

projects[easyopac_nodereferences][type]             = "module"
projects[easyopac_nodereferences][subdir]           = ""
projects[easyopac_nodereferences][download][type]   = "git"
projects[easyopac_nodereferences][download][url]    = "git@github.com:easySuite/easyopac_nodereferences.git"
;projects[easyopac_nodereferences][download][tag]    = ""
projects[easyopac_nodereferences][download][branch] = "development"

projects[easyopac_redirect][type]             = "module"
projects[easyopac_redirect][subdir]           = ""
projects[easyopac_redirect][download][type]   = "git"
projects[easyopac_redirect][download][url]    = "git@github.com:easySuite/easyopac_redirect.git"
;projects[easyopac_redirect][download][tag]    = ""
projects[easyopac_redirect][download][branch] = "development"
