<?php

/**
 * Implementation of hook_theme().
 */
function ting_search_autocomplete_theme() {
  return array();
}

/**
 * Implementation of hook_menu().
 */
function ting_search_autocomplete_menu() {
  $items = array();

  $items['ting/autocomplete'] = array(
    'title'            => 'Ting search autocomplete',
    'description'      => 'Returns a list of suggestions to use for autocompletion',
    'access arguments' => array('search content'),
    'page callback'    => 'ting_search_autocomplete_js',
    'type'             => MENU_CALLBACK,
    'file'             => 'ting_search_autocomplete.pages.inc',
  );

  return $items;
}

/**
 * Implementation of hook_flush_caches().
 */
function ting_search_autocomplete_flush_caches() {
	return array('cache_ting_search_autocomplete');
}

/**
 * Alter the Ting search form to add autocomplete.
 */
function ting_search_autocomplete_form_ting_search_form_alter(&$form, &$form_state) {
	//TODO should this be moved to another hook?
	static $includes_loaded;
	if (!isset($includes_loaded))
	{
		$basePath = drupal_get_path('module', 'ting');
		drupal_add_js($basePath . '/js/jquery-autocomplete-1.0.2-mod/jquery.autocomplete.min.js', 'module', 'footer', TRUE);
		drupal_add_css($basePath . '/js/jquery-autocomplete-1.0.2-mod/jquery.autocomplete.css', 'module');

		$modulePath = drupal_get_path('module', 'ting_search_autocomplete');
		drupal_add_js($modulePath . '/js/ting_search_autocomplete.js', 'module', 'footer', TRUE);

    $autocomple_path = module_exists('trampoline') ? trampoline_url('ting/autocomplete') : url('ting/autocomplete');
    drupal_add_js(array('tingSearchAutocomplete' => array('path' => $autocomple_path)), 'setting');
		drupal_add_css($modulePath . '/css/ting_search_autocomplete.css', 'module');

		$includes_loaded = true;
	}

	$form['keys']['#attributes'] = array('class' => 'ting-autocomplete');
}
