; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"
projects[ctools][patch][0] = "http://drupal.org/files/ctools-n1925018-12.patch"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0"

projects[relation][subdir] = "contrib"
projects[relation][version] = "1.0-rc4"

projects[virtual_field][subdir] = "contrib"
projects[virtual_field][version] = "1.1"

projects[ding_entity][type] = "module"
projects[ding_entity][download][type] = "git"
projects[ding_entity][download][url] = "git@github.com:ding2tal/ding_entity.git"
projects[ding_entity][download][tag] = "7.x-1.0-rc2"

projects[ting][type] = "module"
projects[ting][download][type] = "git"
projects[ting][download][url] = "git@github.com:ding2tal/ting.git"
projects[ting][download][tag] = "7.x-1.0-rc2"

