<?php
/**
 * @file
 * Enables integration with Ting.
 */

define('TING_DEFAULT_CACHE_LIFETIME', 0);
/**
 * Implementation of hook_ctools_plugin_api().
 */
function ting_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 2);
  }
}


/**
 * Implements hook_ctools_plugin_directory() to let the system know
 * where our task and task_handler plugins are.
 */
function ting_ctools_plugin_directory($owner, $plugin_type) {
    return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_ctools_plugin_type() to inform the plugin system that Page
 * Manager owns task, task_handler, and page_wizard plugin types.
 *
 * All of these are empty because the defaults all work.
 */
function ting_ctools_plugin_type() {
  return array(
    'tasks' => array(),
    'content_types' => array(),
    'task_handlers' => array(),
    'page_wizards' => array(),
    'arguments' => array(),
    'contexts' => array(),
  );
}
/**
 * Implements hook_menu().
 */
function ting_menu() {
  $items['ting/object/%ting_object'] = array(
    'title callback' => 'ting_page_title',
    'title arguments' => array(2),
    'page callback' => 'ting_object_page_view',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );

  $items['ting/collection/%ting_collection'] = array(
    'title callback' => 'ting_page_title',
    'title arguments' => array(2),
    'page callback' => 'ting_collection_page_view',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );

  $items['admin/config/ting'] = array(
    'title' => 'Ting',
    'description' => 'Manage Ting integration settings.',
    'position' => 'left',
    'weight' => 20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/ting/settings'] = array(
    'title' => 'Ting',
    'description' => 'Manage Ting integration settings.',
    'weight' => -20,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_admin_ting_settings'),
    'access arguments' => array('administer ting settings'),
    'file' => 'ting.admin.inc'
  );

  $items['admin/config/ting/ranking'] = array(
    'title' => 'Search result ranking',
    'description' => 'Provides settings for how search results are ranked.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_admin_ranking_settings'),
    'access arguments' => array('administer ting settings'),
    'file' => 'ting.admin.inc',
  );

  $items['admin/config/ting/proxy'] = array(
    'title' => 'Proxy settings',
    'description' => 'Ting Proxy settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_admin_proxy_settings'),
    'access arguments' => array('administer ting settings'),
    'file' => 'ting.admin.inc'
  );

  $items['admin/config/ting/registers'] = array(
    'title' => 'Open search register settings',
    'description' => 'Configure registers to use for specific open search searches.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_admin_register_settings'),
    'access arguments' => array('administer ting settings'),
    'file' => 'ting.admin.inc'
  );

  $items['admin/config/ting/online_url'] = array(
    'title' => 'Online URL labels',
    'description' => 'Define labels for online resources.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_admin_online_url_settings'),
    'access arguments' => array('administer ting settings'),
    'file' => 'ting.admin.inc'
  );

  $items['admin/config/ting/reservable'] = array(
    'title' => 'Reservable Ting objects',
    'description' => 'Configure on which Ting objects there will be a reservation button.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_admin_reservable_settings'),
    'access arguments' => array('administer ting settings'),
    'file' => 'ting.admin.inc'
  );

  return $items;
}

/**
 * Implements hook_ding_install_tasks().
 */
function ting_ding_install_tasks() {
  module_load_include('inc', 'ting', 'ting.admin');
  return array(
    'ting_admin_ting_settings' => array(
      'display_name' => st('Ting service settings'),
      'type' => 'form',
      'file' => drupal_get_path('module', 'ting') . '/ting.admin.inc',
    ),
    'ting_admin_proxy_settings' => array(
      'display_name' => st('Proxy service settings'),
      'type' => 'form',
      'file' => drupal_get_path('module', 'ting') . '/ting.admin.inc',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function ting_permission() {
  return array(
    'administer ting settings' => array(
      'title' => t('Administer ting settings'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function ting_block_info() {
  return array(
    'ting_collection_types' => array(
      'info' => t('Ting collection material types'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ),
    'ting_object_types' => array(
      'info' => t('Ting alternative material types'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function ting_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'ting_collection_types':
      if ($collection = menu_get_object('ting_collection', 2)) {
        $block['subject'] = array(
          '#markup' => t('Types'),
          '#prefix' => '<div class="ting-collection-types-header">',
          '#suffix' => '</div>',
        );
        $block['subject'] = render($block['subject']);
        $items = array();
        foreach ($collection->types as $type) {
          $items[] = l($type, '#' . $type, array('external' => TRUE));
        }
        $block['content'] = array(
          '#theme' => 'item_list',
          '#items' => $items,
        );
      }
      break;
    case 'ting_object_types':
      if (($object = menu_get_object('ting_object', 2)) &&
        ($collection = ting_collection_load($object->id))) {
        $block['subject'] = array(
          '#markup' => t('Types'),
          '#prefix' => '<div class="ting-object-types-header">',
          '#suffix' => '</div>',
        );
        $block['subject'] = render($block['subject']);
        $items = array();
        foreach ($collection->types as $type) {
          $uri = entity_uri('ting_collection', $collection);
          $uri['options']['fragment'] = $type;
          $items[] = l($type, $uri['path'], $uri['options']);
        }

        $block['content'] = array(
          '#theme' => 'item_list',
          '#items' => $items,
        );
      }
    break;
  }

  return $block;
}

/**
 * Implements hook_element_info().
 *
 * Define a new form element named ting_ranking_field.
 *
 * It calls the theme function theme_ting_ranking_field, if not defined
 * no elements will be displayed.
 */
function ting_element_info() {
  return array(
    'ting_ranking_field' => array(
      '#input' => TRUE,
      '#process' => array('ting_ranking_field_element_process'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function ting_theme() {
  return array(
    'ting_object' => array(
      'template' => 'ting_object',
      'render element' => 'elements',
      'file' => 'ting.theme.inc',
    ),
    'ting_object_overview' => array(
      'template' => 'ting_object_overview',
      'render element' => 'elements',
      'file' => 'ting.theme.inc',
    ),
    'ting_object_details' => array(
      'template' => 'ting_object_details',
      'render element' => 'elements',
      'file' => 'ting.theme.inc',
    ),
    'ting_ranking_field' => array(
      'arguments' => array('element' => NULL),
    ),

  );
}

/**
 * Implements hook_ding_devel_timers().
 */
function ting_ding_devel_timers() {
  return array(
    'ting' => array(
      'title' => 'Ting total request time was @time ms.',
    ),
    'ting_net' => array(
      'title' => 'Ting net time was @time ms.',
      'include in total' => FALSE,
    )
  );
}

/**
 * Implements hook_entity_info().
 */
function ting_entity_info() {
  $return = array(
    'ting_object' => array(
      'label' => t('Ting object'),
      'controller class' => 'TingObjectController',
      'base table' => 'ting_object',
      'revision table' => 'ting_object_revision',
      'uri callback' => 'ting_object_uri',
      'ding_entity_type' => 'ding_entity',
      'ding_entity_menu' => 'ting/object/%ting_object',
      'ding_entity_index' => 2,
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'tid',
        'revision' => 'vid',
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        ),
        'teaser' => array(
          'label' => t('Teaser'),
          'custom settings' => TRUE,
        ),
        'listing' => array(
          'label' => t('Listing'),
          'custom settings' => FALSE,
        ),
      ),
    ),

    'ting_collection' => array(
      'label' => t('Ting collection'),
      'controller class' => 'TingCollectionController',
      'uri callback' => 'ting_collection_uri',
      'ding_entity_type' => 'ding_entity_collection',
      'ding_entity_menu' => 'ting/collection/%ting_collection',
      'ding_entity_index' => 2,
      'entity keys' => array(
        // We don't really have an ID, but use the ding_entity_collection_id,
        // so we can use entity_uri.
        'id' => 'ding_entity_collection_id',
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        ),
        'teaser' => array(
          'label' => t('Teaser'),
          'custom settings' => TRUE,
        ),
        'listing' => array(
          'label' => t('Listing'),
          'custom settings' => FALSE,
        ),
      ),
    ),
  );

  return $return;
}

/**
 * Implements hook_registry_files_alter().
 */
function ting_registry_files_alter(&$files, $modules) {
  // Add in ting client classes, so the autoloader knows where to find
  // them. This is more handy than hardcoding them into the info file.
  $def = array(
    'module' => 'ting',
    'weight' => 0,
  );

  // Add all of the Ting client library to the registry.
  foreach (file_scan_directory(drupal_get_path('module', 'ting') . '/lib/ting-client/lib', '/\.php$/') as $filename => $dummy) {
    $files[$filename] = $def;
  }

  // And the Ting client unit tests as well.
  foreach (file_scan_directory(drupal_get_path('module', 'ting') . '/lib/ting-client/tests', '/\.test$/') as $filename => $dummy) {
    $files[$filename] = $def;
  }
}

/**
 * Implements hook_ding_entity_is().
 */
function ting_ding_entity_is($object, $class) {
  if ($class == 'reservable' || $class == 'cartable') {
    $sources = variable_get('ting_reservable_sources', _ting_default_reservable_sources());
    $types = variable_get('ting_reservable_types', _ting_default_reservable_types());
    if (isset($sources[drupal_strtolower($object->ac_source)]) && isset($types[drupal_strtolower($object->type)])) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
}

/**
 * Implements hook_page_alter().
 *
 * Log, and display if the devel module is active and the user has
 * permissions, a warning if the datawell was queried more than once.
 */
function ting_page_alter(&$page) {
  $calls = &drupal_static('ting_execute_cache');
  if (sizeof($calls) > 1) {
    $calls_str = array();
    foreach ($calls as $call) {
      $calls_str[] = print_r($calls, TRUE);
    }
    watchdog('ting', 'Warning, ting_execute called @x times:<br />"@queries"', array('@x' => sizeof($calls), '@queries' => join('" "', $calls_str)), WATCHDOG_WARNING);
    if (function_exists('dpm') && user_access('access devel information')) {
      drupal_set_message(t('Warning, ting_execute called @x times.', array('@x' => sizeof($calls))), 'error');
      dpm($calls, 'ting_execute queries:');
    }
  }
}

/**
 * Page callback: Display a ting object.
 */
function ting_object_page_view($object) {
  return ting_object_view($object);
}

/**
 * Page callback: Display a ting collection.
 */
function ting_collection_page_view($object) {
  if (sizeof($object->entities) < 2) {
    drupal_goto('ting/collection/' . $object->id);
  }
  return ting_collection_view($object);
}

/**
 * Page title callback.
 */
function ting_page_title($object) {
  return check_plain($object->title);
}

/**
 * Callback for entity_uri(). Returns the uri for the object.
 */
function ting_object_uri($collection) {
  return array('path' => 'ting/object/' . $collection->id);
}

/**
 * Callback for entity_uri(). Returns the uri for the collection.
 */
function ting_collection_uri($collection) {
  if (sizeof($collection->entities) > 1) {
    return array('path' => 'ting/collection/' . $collection->id);
  }
  else {
    return entity_uri('ting_object', $collection->primary_object);
  }
}

/**
 * Add a provider_id to the objects.
 *
 * @todo
 *   Maybe this should be in a mapper module.
 */
function ting_ting_object_load($objects) {
  foreach ($objects as $object) {
    $object->provider_id = $object->localId;
  }
}

/**
 * Load a ting object.
 */
function ting_object_load($id) {
  $object = entity_load('ting_object', array(), array('ding_entity_id' => array($id)));
  return $object ? reset($object) : FALSE;
}

/**
 * Load a ting object.
 */
function ting_object_load_multiple($ids) {
  return entity_load('ting_object', array(), array('ding_entity_id' => $ids));
}

/**
 * Load a ting collection.
 */
function ting_collection_load($id) {
  $conditions = array('ding_entity_collection_id' => array($id));

  $collection = entity_load('ting_collection', array(), $conditions);
  return $collection ? reset($collection) : FALSE;
}

/**
 * Display a ting object.
 */
function ting_object_view($object, $view_mode = 'full') {
  $object->content = array();
  $object->content['actions'] = array();
  $object->content['overview'] = array(
    '#theme' => 'ting_object_overview',
    '#object' => $object,
    '#view_mode' => $view_mode,
    'left' => array(),
    'right' => array(),
  );

  if ($view_mode == 'full') {
    $object->content['details'] = array(
      '#theme' => 'ting_object_details',
      '#object' => $object,
      '#view_mode' => $view_mode,
    );
  }

  if (isset($object->online_url)) {
    $settings = variable_get('ting_url_labels', _ting_default_url_labels());
    $type = drupal_strtolower($object->type);
    $label = isset($settings[$type]) && $settings[$type] ? $settings[$type] : $settings['_default'];
    $object->content['actions'][] = array(
      '#type' => 'markup',
      '#markup' => l($label, $object->online_url),
    );

  }

  field_attach_prepare_view('ting_object', array($object->id => $object), $view_mode);
  entity_prepare_view('ting_object', array($object->id => $object));
  $object->content += field_attach_view('ting_object', $object, $view_mode);

  // Allow modules to make their own additions to the object.
  module_invoke_all('ding_entity_view', $object, $view_mode);
  module_invoke_all('entity_view', $object, 'ting_object', $view_mode);

  $build = $object->content;
  unset($object->content);

  $build += array(
    '#theme' => 'ting_object',
    '#object' => $object,
    '#view_mode' => $view_mode,
  );

  drupal_alter('ting_view', $build);

  return $build;
}

/**
 * Display a ting collection.
 */
function ting_collection_view($object, $view_mode = 'full') {
  $object->content = array();
  $object->content['actions'] = array();
  $object->content['overview'] = array(
    '#theme' => 'ting_object_overview',
    '#object' => $object->primary_object,
    '#view_mode' => $view_mode,
    'left' => array(),
    'right' => array(),
  );

  if ($view_mode == 'full') {
    foreach ($object->types as $type) {
      $object->content['entities'][$type] = array(
        '#prefix' => '<h2>' . $type . '</h2><a name="' . $type . '"></a>',
      );
    }
    foreach ($object->entities as $entity) {
      $object->content['entities'][$entity->type][$entity->id] = ting_object_view($entity, 'teaser');
    }
  }
  entity_prepare_view('ting_collection', array($object->id => $object));

  // Allow modules to make their own additions to the collection.
  module_invoke_all('ding_entity_collection_view', $object, $view_mode);
  module_invoke_all('entity_view', $object, 'ting_collection', $view_mode);

  $build = $object->content;
  unset($object->content);

  $build += array(
    // TODO: Separate theming?
    '#theme' => 'ting_object',
    '#object' => $object,
    '#view_mode' => $view_mode,
  );

  drupal_alter('ting_view', $build);
  return $build;
}

/**
 * Sorts the objects according to type and language, but maintains the order
 * of types and languages in the original array.
 */
function _ting_type_lang_sort($objects, &$return_types) {
  $types = array();
  $language = array();
  $sorted = array();
  // Sort the objects into type buckets containing language buckets.
  foreach ($objects as $object) {
    // We're using keys so we don't have to uniq its afterwards.
    $types[$object->type] = TRUE;
    $languages[$object->language] = TRUE;
    $buckets[$object->type][$object->language][] = $object;
  }

  $return_types = array_keys($types);
  // Now flatten the buckets into a flat array.
  foreach ($return_types as $type) {
    foreach (array_keys($languages) as $language) {
      if (isset($buckets[$type][$language])) {
        $sorted = array_merge($sorted, $buckets[$type][$language]);
      }
    }
  }

  return $sorted;
}

/**
 * Default url labels.
 *
 * Defined as a function as a define can only be scalars.
 */
function _ting_default_url_labels() {
  return array(
    '_default' => t('See online'),
    'cd' => t('Hear online'),
    'kassettelydbånd' => t('Hear online'),
    'lydbog (cd)' => t('Hear online'),
    'lydbog (cd-mp3)' => t('Hear online'),
    'lydbog (online)' => t('Hear online'),
    'grammofonplade' => t('Hear online'),
  );
}

/**
 * Processor for the ting_ranking_field form element.
 */
function ting_ranking_field_element_process($element, $form_state) {
  $element['#tree'] = TRUE;
  $element['#prefix'] = '<div class="ting-ranking-field-element clearfix">';
  $element['#suffix'] = '</div>';

  $element['field_type'] = array(
    '#title' => t('Type'),
    '#type' => 'select',
    '#options' => array(
      'phrase' => t('Phrase'),
      'word' => t('Word'),
    ),
    '#default_value' => (isset($element['#value']['field_type'])) ? $element['#value']['field_type'] : NULL,
  );

  $element['field_name'] = array(
    '#title' => t('Field name'),
    '#type' => 'select',
    '#options' => array(
      '' => '- ' . t('Choose') . ' -',
      'dc.source' => t('Source'),
      'dc.title' => t('Title'),
      'dc.creator' => t('Author'),
      'dc.subject' => t('Subject'),
      'dc.date' => t('Year of publish'),
      'dc.type' => t('Material type'),
    ),
    '#default_value' => (isset($element['#value']['field_name'])) ? $element['#value']['field_name'] : NULL,
    '#attributes' => array('class' => array('field-name')),
  );

  $element['weight'] = array(
    '#title' => t('Weight'),
    '#type' => 'select',
    '#options' => drupal_map_assoc(range(1, 10)),
    '#default_value' => (isset($element['#value']['weight'])) ? $element['#value']['weight'] : NULL,
  );

  return $element;
}

/**
 * Theme function to format the custom form element ting_ranking_field.
 */
function theme_ting_ranking_field($element) {
  return theme('form_element', $element);
}

/**
 * Default reservable sources.
 *
 * Defined as a function as a define can only be scalars.
 */
function _ting_default_reservable_sources() {
  return drupal_map_assoc(array(
    'bibliotekets materialer',
  ));
}

/**
 * Default reservable types.
 *
 * Defined as a function as a define can only be scalars.
 */
function _ting_default_reservable_types() {
  return drupal_map_assoc(array(
    'billedbog',
    'blu-ray disc',
    'bog',
    'cd',
    'cd-rom',
    'diskette',
    'dvd',
    'dvd-rom',
    'film',
    'grammofonplade',
    'kassettelydbånd',
    'lydbog (cd)',
    'lydbog (cd-mp3)',
    'periodikum',
    'playstation2-spil',
    'playstation3-spil',
    'playstation-spil',
    'puslespil',
    'spil',
    'tegneserie',
    'video',
    'wii-spil',
    'xbox-spil',
    'årbog',
  ));
}

/**
 * Fetch known types from the datawell.
 */
function _ting_fetch_well_types() {
  // Get a list of types by executing a null query and look at the facets
  // result.
  $options = array(
    'facets' => array('facet.type'),
    'numFacets' => 99,
    'reply_only' => TRUE,
    'sort' => 'random',
  );
  module_load_include('client.inc', 'ting');
  $result = ting_do_search("*=*", 0, 0, $options);

  $types = array();
  foreach ($result->facets['facet.type']->terms as $term => $count) {
    $types[drupal_strtolower($term)] = $count;
  }

  // Only save if we actually got any types.
  if (!empty($types)) {
    variable_set('ting_well_types', $types);
  }
}

/**
 * Fetch known sources from the datawell.
 */
function _ting_fetch_well_sources() {
  // Get a list of sources by executing a null query and look at the facets
  // result.
  $options = array(
    'facets' => array('facet.acSource'),
    'numFacets' => 99,
    'reply_only' => TRUE,
    'sort' => 'random',
  );
  module_load_include('client.inc', 'ting');
  $result = ting_do_search("*=*", 0, 0, $options);

  $sources = array();
  foreach ($result->facets['facet.acSource']->terms as $term => $count) {
    $sources[drupal_strtolower($term)] = $count;
  }

  // Only save if we actually got any types.
  if (!empty($sources)) {
    variable_set('ting_well_sources', $sources);
  }
}
