<?php

/**
 * @file
 * Translated search.
 */

use GuzzleHttp\Client as HttpClient;
use GuzzleHttp\Exception\ClientException as GuzzleClientException;

// Load Field module hooks.
module_load_include('inc', 'ting_subsearch_translate', 'ting_subsearch_translate.admin');

/**
 * Implements hook_ting_search_results_prefix().
 */
function ting_subsearch_translate_ting_search_results_prefix($keys, $conditions, \Ting\Search\TingSearchResultInterface $results) {
  $message = '';

  if (!$results->getNumTotalObjects()) {
    return $message;
  }

  // If no google api key is set we cannot translate.
  if (empty(variable_get('ting_subsearch_translate_google_key', ''))) {
    return $message;
  }

  $facets = $results->getFacets();

  // If any of fiction or non fiction is empty we cannot do the calculation.
  // Simply exit for now.
  if (!isset($facets['facet.genreCategory'])) {
    watchdog('subsearch_translate', 'You need to enable facet.genreCategory in order for this to work.', array(), WATCHDOG_WARNING);
    return $message;
  }

  $terms = $facets['facet.genreCategory']->getTerms();
  $nonfiction = isset($terms['nonfiktion']) ? $terms['nonfiktion']->getCount() : 0;
  $fiction = isset($terms['fiktion']) ? $terms['fiktion']->getCount() : 0;

  // Less than half fiction of nonfiction.
  if (($nonfiction / variable_get('ting_subsearch_translate_factor', 2)) > $fiction) {

    $translated_keys = ting_subsearch_common_suggested_keys($keys, 'ting_subsearch_translate_suggest_translated_keys');
    if (strtolower($translated_keys) == strtolower($results->getSearchRequest()->getFullTextQuery())) {
      // The two search are the same. So no need to do extra search query.
      return $message;
    }

    $suggested_result = ting_subsearch_common_do_secondary_search($translated_keys);
    $num_total_objects = $suggested_result->getNumTotalObjects();
    if (!empty($num_total_objects)) {
      $msg = t('The search for "!keys" gave !num-results hits. If you search for the English translation "!suggested-keys-link" you will get !suggested-num-results hits.', array(
        '!suggested-keys-link' => l(strtolower($translated_keys), '/search/ting/'  . strtolower($translated_keys) ),
        '!suggested-num-results' => $suggested_result->getNumTotalObjects(),
        '!keys' => $keys,
        '!num-results' => $results->getNumTotalObjects(),
      ));
      $message = '<div class="messages search-field-in-content--message">' . $msg . '</div>';
    }

  }
  return $message;
}

/**
 * Finds suggested keys based on Google translation.
 */
function ting_subsearch_translate_suggest_translated_keys($keys) {

  // @TODO: Don't hardcode URL to service into module.
  $url = 'https://www.googleapis.com/language/translate/v2';

  $params = [];
  $params['q'] = $keys;
  $params['key'] = variable_get('ting_subsearch_translate_google_key', '');
  $params['source'] = 'da';
  $params['target'] = 'en';

  try {
    $client = new HttpClient();
    $response = $client->get(
      $url,
      array(
        'query' => $params,
        'headers' => array(
          'Accept' => 'application/json',
        ),
      )
    );
    $result = json_decode($response->getBody());
  }
  catch (GuzzleClientException $e) {
    throw new Exception($e->getMessage(), $e->getCode(), $e);
  }

  if (!empty($result->data->translations[0]->translatedText)) {
    return $result->data->translations[0]->translatedText;
  }
}
