; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.5"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[virtual_field][subdir] = "contrib"
projects[virtual_field][version] = "1.2"

projects[ting][type] = "module"
projects[ting][download][type] = "git"
projects[ting][download][url] = "git@github.com:ding2/ting.git"
projects[ting][download][branch] = "master"

