<?php

/**
 * @file
 * Ting subsearch using Bibliotek.dk service.
 */

use Ting\Search\NullSearchResult;

// Load admin configuration.
module_load_include('inc', 'ting_subsearch_secondary', 'ting_subsearch_secondary.admin');
include_once 'ting_subsearch_secondary.features.inc';

/**
 * Implements hook_ting_search_results_prefix().
 *
 * @throws \Exception
 */
function ting_subsearch_secondary_ting_search_results_prefix($keys, $conditions, $results) {
  if (variable_get('ting_subsearch_secondary_position', 'before') == 'before') {
    return ting_subsearch_secondary_search($keys, $results);
  }
}

/**
 * Implements hook_ting_search_results_suffix().
 *
 * @throws \Exception
 */
function ting_subsearch_secondary_ting_search_results_suffix($keys, $conditions, $results) {
  if (variable_get('ting_subsearch_secondary_position', 'before') == 'after') {
    return ting_subsearch_secondary_search($keys, $results);
  }
}

/**
 * Implements hook_ting_search_results_suffix().
 *
 * @throws \Exception
 */
function ting_subsearch_secondary_search($keys, $results) {
  $message = '';

  if ($results instanceof NullSearchResult) {
    return;
  }

  if (!empty($results->numTotalObjects)) {
    if ($results->numTotalObjects > variable_get('ting_subsearch_secondary_min', 10) && $results->numTotalObjects < variable_get('ting_subsearch_secondary_max', 100)) {
      $facets = $results->getFacets();
      $genre_facets = $facets['facet.genreCategory']->getTerms();
      // If any of fiction or non fiction is empty we cannot do the calculation.
      // Simply exit for now.
      if (empty($facets['facet.genreCategory'])) {
        watchdog('subsearch_subsearch', 'You need to enable facet.genreCategory in order for this to work.', [], WATCHDOG_WARNING);
        return $message;
      }

      if (empty(variable_get('ting_subsearch_secondary_agency', '')) || empty(variable_get('ting_subsearch_secondary_profile', ''))) {
        watchdog('subsearch_subsearch', 'Missing secondary agency or profile.', [], WATCHDOG_WARNING);
        return $message;
      }

      $nonfiction = 1;
      if (!empty($genre_facets['nonfiktion'])) {
        $nonfiction = $genre_facets['nonfiktion']->getCount();
      }

      $fiction = 0;
      if (!empty($genre_facets['fiktion'])) {
        $fiction = $genre_facets['fiktion']->getCount();
      }

      // Less than half fiction of nonfiction.
      if (($nonfiction / variable_get('ting_subsearch_secondary_factor', 2)) > $fiction) {
        $message = ting_subsearch_secondary_execute_secondary_search($keys, $results);
      }
    }
  }
  else {
    $message = ting_subsearch_secondary_execute_secondary_search($keys, $results);
  }
  return $message;
}

/**
 * Execute secondary search.
 * @param $keys
 * @param $results
 *
 * @return string
 * @throws \Exception
 */
function ting_subsearch_secondary_execute_secondary_search($keys, $results) {
  $message = '';
  $secondary_result = ting_subsearch_common_do_secondary_search($keys, [
    'agency' => variable_get('ting_subsearch_secondary_agency', ''),
    'profile' => variable_get('ting_subsearch_secondary_profile', ''),
  ]);

  if ($secondary_result->numTotalObjects > variable_get('ting_subsearch_secondary_result_min', 100)) {
    $items = [];

    $number_of_records_to_show = variable_get('ting_subsearch_secondary_number_of_results', 4);
    foreach ($secondary_result->collections as &$collection) {
      if ($number_of_records_to_show == 0) {
        continue;
      }
      else {
        $number_of_records_to_show--;
      }
      $build = ting_collection_view($collection, 'minimal');
      $items[] = drupal_render($build);
    }

    $options = [
      '!link' => str_replace('[keys]', urlencode($keys), variable_get('ting_subsearch_secondary_search_link', '')),
      '!link-text' => variable_get('ting_subsearch_secondary_search_link_text', ''),
      '!keys' => $keys,
      '!num-results' => $results->getNumTotalObjects(),
      '!bibdk-num-results' => $secondary_result->numTotalObjects,
      '!examples' => theme('item_list', ['items' => $items]),
    ];

    if (variable_get('ting_subsearch_secondary_number_of_results', 4) == 0) {
      $msg = t('If you search for "!keys" on !link-text instead you will get !bibdk-num-results hits',
        $options
      );
    }
    else {
      $msg = t('If you search for "!keys" on !link-text instead you will get !bibdk-num-results hits where some of them is the following: !examples',
        $options
      );
    }
    $wrapper = '<div class="messages search-field-in-content--message">' . $msg . '</div>';
    $message = l($wrapper, $options['!link'], [
      'html' => TRUE,
      'absolute' => TRUE,
      'attributes' => ['target' => 'blank']
    ]);
    drupal_add_css(drupal_get_path('module', 'ting_subsearch_secondary') . '/ting_subsearch_secondary.css');
  }

  return $message;
}

/**
 * Implements hook_entity_info_alter().
 */
function ting_subsearch_secondary_entity_info_alter(&$entity_info) {
  $entity_info['ting_object']['view modes']['minimal'] = array(
    'label' => t('Minimal'),
    'custom settings' => TRUE,
  );
  $entity_info['ting_collection']['view modes']['minimal'] = array(
    'label' => t('Minimal'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function ting_subsearch_secondary_field_formatter_info() {
  return array(
    'ting_title_minimal' => array(
      'label' => t('Minimal Title'),
      'field types' => array(
        'ting_title',
      ),
      'settings' => array(
        'link_type' => 'none',
        'prefix_type' => 'no',
      ),
    ),

    'ting_author_minimal' => array(
      'label' => t('Minimal author'),
      'field types' => array(
        'ting_author',
      ),
    ),
  );
}


/**
 * Implements hook_field_formatter_view().
 */
function ting_subsearch_secondary_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    switch ($display['type']) {
      case 'ting_title_minimal':
        // Only create the link if the object is available in the data well.
        $title = check_plain($entity->title);
        $element[$delta] = array(
          '#prefix' => '<h2 class="ting-object-minimal-title">',
          '#suffix' => '</h2>',
          '#markup' => $title,
        );
        break;

      case 'ting_author_minimal':
        $creators = array();
        foreach ($entity->creators as $i => $creator) {
          $creators[] = $creator;
        }
        $markup_string = '';
        if (count($creators)) {
          if ($entity->date != '') {
            $markup_string = t('By !author_link (@year)', array(
              '!author_link' => implode(', ', $creators),
              // So wrong, but appears to be the way the data is.
              '@year' => $entity->date,
            ));
          }
          else {
            $markup_string = t('By !author_link', array(
              '!author_link' => implode(', ', $creators),
            ));
          }
        }
        elseif ($entity->date != '') {
          $markup_string = t('(@year)', array('@year' => $entity->date));
        }
        $element[$delta] = array(
          '#markup' => $markup_string,
        );
        break;

    }
  }

  return $element;
}
