<?php

/**
 * @file
 * Implements an extended search form with fields for librarians.
 *
 * Adds several input fields to search in specific indexes.
 */

/**
 * @brief Implementation of hook_menu()
 */
function ting_search_extendform_menu() {
  $items['admin/config/ting/searchextendform'] = 
    array(
      'title' => 'Extended search form settings',
      'description' => 'Change how the extended search form behaves',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ting_search_extendform_admin_settings'),
      'access arguments' => array('administer ting settings'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'searchextendform.admin.inc'
          );

  return $items;
}

/**
 * @brief Implementation of hook_form_FORM_ID_alter() for form search_block_form.
 */
function ting_search_extendform_form_search_block_form_alter(&$form, &$form_state, $form_id) {
  $form['advanced_search'] = 
    array('#type' => 'fieldset',
          '#title' => t('Advanseret'),
          '#collapsible' => TRUE,
          '#collapsed' => TRUE,
      	  '#attributes' => array('class' => array('extendsearch-advanced')),
      	  '#prefix' => '<br/>'
         );

  $form['advanced_search']['fields'] =
    array(
      '#prefix' => '<div class="fields">',
      '#suffix' => '</div>',
    );     
    
  $form['advanced_search']['fields']['ting_search_extendform_creator_field'] = 
    array('#type' => 'textfield',
      	  '#title' => t('Forfatter:'),
      	  '#size' => 30,
      	  '#maxlength' => 255,
    );
  $form['advanced_search']['fields']['ting_search_extendform_title_field'] = 
    array('#type' => 'textfield',
      	  '#title' => t('Titel:'),
      	  '#prefix' => '<br/>',
    	  '#size' => 30,
      	  '#maxlength' => 255,
    );
  $form['advanced_search']['fields']['ting_search_extendform_subject_field'] = 
    array('#type' => 'textfield',
      	  '#title' => t('Emne:'),
      	  '#prefix' => '<br/>',
    	  '#size' => 30,
      	  '#maxlength' => 255,
    );
	  
  dpm($form);
  return $form;
}
