<?php
/**
 * @file
 * Extending opening hours to match the ddbasic theme.
 */

/**
 * Implements hook_menu().
 */
function ding_ddbasic_opening_hours_menu() {
  $items = array();

  $items['admin/config/ding/ddbasic-opening-hours'] = array(
    'title' => 'Ding DDBasic opening hours',
    'description' => 'Opening hours settings for the DDBasic theme',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_ddbasic_opening_hours_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_ddbasic_opening_hours.admin.inc',
  );

  $items['ding-ddbasic/opening-hours/week/%node/%/%'] = array(
    'title' => 'Opening hours',
    'page callback' => 'ding_ddbasic_opening_hours_week_callback',
    'page arguments' => array(3, 4, 5),
    'delivery callback' => 'ajax_deliver',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'ding_ddbasic_opening_hours.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function ding_ddbasic_opening_hours_init() {
  $item = menu_get_item();
  if ($item['path'] === 'node/%') {
    $node = menu_get_object();
    if ($node->type === 'ding_library' && variable_get('ding_ddbasic_opening_hours_expand_on_library', FALSE)) {
      drupal_add_js(array('ding_ddbasic_opening_hours_expand_on_library' => TRUE), 'setting');
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_ddbasic_opening_hours_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_theme().
 *
 * - All opening hours theme.
 */
function ding_ddbasic_opening_hours_theme($existing, $type, $theme, $path) {
  return array(
    'ding_ddbasic_opening_hours_all' => array(
      'file' => 'ding_ddbasic_opening_hours.theme.inc',
      'variables' => array(
        'today' => NULL,
      ),
    ),
  );
}
