<?php

/**
 * @file
 * Translated search.
 */

use GuzzleHttp\Client as HttpClient;
use GuzzleHttp\Exception\ClientException as GuzzleClientException;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ting_subsearch_translate_form_ting_subsearch_admin_settings_form_alter(&$form, &$form_state) {
  $form['subsearch']['translate'] = [
    '#type' => 'fieldset',
    '#title' => t('Translation Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  ];
  $form['subsearch']['translate']['trigger'] = [
    '#type' => 'fieldset',
    '#title' => t('Trigger'),
  ];
  $form['subsearch']['translate']['trigger']['ting_subsearch_translate_factor'] = [
    '#type' => 'textfield',
    '#title' => t('Ratio between nonfiction and fiction'),
    '#description' => t('The ratio of nonfiction more than fiction to trigger the translation'),
    '#default_value' => variable_get('ting_subsearch_translate_factor', 50),
    '#element_validate' => ['ting_subsearch_factor_field_validate'],
  ];

  $form['subsearch']['translate']['trigger']['ting_subsearch_translate_ps_factor'] = [
    '#type' => 'textfield',
    '#title' => t('Ratio between primary and secondary searches'),
    '#description' => t('The ratio between primary and secondary searches to trigger the translation.'),
    '#default_value' => variable_get('ting_subsearch_translate_ps_factor', 10),
    '#element_validate' => ['ting_subsearch_factor_field_validate'],
  ];

  $form['subsearch']['translate']['ting_subsearch_translate_url'] = [
    '#type' => 'textfield',
    '#title' => t('Google translation service url'),
    '#description' => t('Google Translation API endpoint. <strong>Example:</strong> https://www.googleapis.com/language/translate/v2'),
    '#default_value' => variable_get('ting_subsearch_translate_url', 'https://www.googleapis.com/language/translate/v2'),
  ];

  $form['subsearch']['translate']['ting_subsearch_translate_google_key'] = [
    '#type' => 'textfield',
    '#title' => t('Google Cloud Translation API key'),
    '#description' => t('You need to have an API key configured with billing for this to work. take a look at <a href="https://cloud.google.com/translate/pricing">Pricing</a>'),
    '#default_value' => variable_get('ting_subsearch_translate_google_key', ''),
  ];
}

/**
 * Implements hook_ting_subsearch_ajax_callback().
 */
function ting_subsearch_translate_ting_subsearch_ajax_callback($original_search, $original_search_num_results) {
  $message = '';

  $suggestion = ting_subsearch_translate_suggest_translated_keys($original_search);

  if (!$suggestion) {
    return $message;
  }

  // The two search are the same, so avoid doing secondary search.
  if (drupal_strtolower($suggestion) == drupal_strtolower($original_search)) {
    return $message;
  }

  $suggestion_result = ting_subsearch_do_secondary_search($suggestion);
  $suggestion_num_results = $suggestion_result->getNumTotalObjects();

  // No reason to continue if the suggestion didn't provide any results.
  if ($suggestion_num_results == 0) {
    return $message;
  }

  $factor = variable_get('ting_subsearch_translate_ps_factor', 10);

  if ($original_search_num_results == 0 || $suggestion_num_results / $original_search_num_results >= $factor) {
    $message = t('Search in english <strong>"@suggestion"</strong> - returns <strong>!suggestion-num-results</strong> hits', [
      '@suggestion' => $suggestion,
      '!suggestion-num-results' =>  $suggestion_num_results,
    ]);

    $message = theme('ting_subsearch_message', [
      'message' => l($message, 'search/ting/' . $suggestion, [
        'html' => TRUE,
        'attributes' => ['target' => 'blank'],
        'query' => drupal_get_query_parameters(),
      ]),
      'type' => 'translate',
      'suggestion' => $suggestion,
      'suggestion_num_results' => $suggestion_num_results,
      'original_search' => $original_search,
      'original_search_num_results' => $original_search_num_results,
    ]);
  }

  return $message;
}

/**
 * Implements hook_ting_search_results_prefix().
 */
function ting_subsearch_translate_ting_search_results_prefix($keys, $conditions, $results) {
  // Return early if module is not configured.
  if (empty(variable_get('ting_subsearch_translate_google_key', ''))) {
    return;
  }

  $original_search_num_results = $results->getNumTotalObjects();
  $factor = variable_get('ting_subsearch_translate_factor', 50);
  $ratio = ting_subsearch_get_genre_ratio($results);

  // Activate subsearch translation if the original search has zero hits or if
  // the genre category ratio satifies the factor.
  if ($original_search_num_results == 0 || $ratio >= $factor) {
    return theme('ting_subsearch_ajax_trigger', [
      'original_search' => $keys,
      'original_search_num_results' => $original_search_num_results,
      'module' => 'ting_subsearch_translate',
    ]);
  }
}

/**
 * Finds suggestion based on Google translation.
 *
 * @param $original_search
 *   The original search phrase.
 *
 * @return string|bool
 *   The translation or FALSE if no translation was obtained.
 */
function ting_subsearch_translate_suggest_translated_keys($original_search) {
  $original_search = ting_subsearch_normalize_keys($original_search);

  $params = [];
  $params['q'] = $original_search;
  $params['key'] = variable_get('ting_subsearch_translate_google_key', '');
  $params['source'] = 'da';
  $params['target'] = 'en';

  try {
    $client = new HttpClient();
    $response = $client->get(
      variable_get('ting_subsearch_translate_url', 'https://www.googleapis.com/language/translate/v2'),
      [
        'query' => $params,
        'headers' => [
          'Accept' => 'application/json',
        ],
      ]
    );
    $result = json_decode($response->getBody());

    if (!empty($result->data->translations[0]->translatedText)) {
      $translation = (string) $result->data->translations[0]->translatedText;
      return html_entity_decode($translation, ENT_QUOTES);
    }
  } catch (GuzzleClientException $e) {
    watchdog_exception('ting_subsearch_translate', $e);
    return FALSE;
  }

  return FALSE;
}
