; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.5"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.8"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0-beta1"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[relation][subdir] = "contrib"
projects[relation][version] = "1.0-rc5"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[ding_adhl_frontend][type] = "module"
projects[ding_adhl_frontend][download][type] = "git"
projects[ding_adhl_frontend][download][url] = "git@github.com:ding2/ding_adhl_frontend.git"
projects[ding_adhl_frontend][download][branch] = "master"

projects[ding_facetbrowser][type] = "module"
projects[ding_facetbrowser][download][type] = "git"
projects[ding_facetbrowser][download][url] = "git@github.com:ding2/ding_facetbrowser.git"
projects[ding_facetbrowser][download][branch] = "master"

projects[ding_frontend][type] = "module"
projects[ding_frontend][download][type] = "git"
projects[ding_frontend][download][url] = "git@github.com:ding2/ding_frontend.git"
projects[ding_frontend][download][branch] = "master"

projects[ting_search][type] = "module"
projects[ting_search][download][type] = "git"
projects[ting_search][download][url] = "git@github.com:ding2/ting_search.git"
projects[ting_search][download][branch] = "master"

projects[ting_search_autocomplete][type] = "module"
projects[ting_search_autocomplete][download][type] = "git"
projects[ting_search_autocomplete][download][url] = "git@github.com:ding2/ting_search_autocomplete.git"
projects[ting_search_autocomplete][download][branch] = "master"

projects[ding_availability][type] = "module"
projects[ding_availability][download][type] = "git"
projects[ding_availability][download][url] = "git@github.com:ding2/ding_availability.git"
projects[ding_availability][download][branch] = "master"

projects[ding_periodical][type] = "module"
projects[ding_periodical][download][type] = "git"
projects[ding_periodical][download][url] = "git@github.com:ding2/ding_periodical.git"
projects[ding_periodical][download][branch] = "master"

projects[ting_relation][type] = "module"
projects[ting_relation][download][type] = "git"
projects[ting_relation][download][url] = "git@github.com:ding2/ting_relation.git"
projects[ting_relation][download][branch] = "master"

projects[ding_toggle_format][type] = "module"
projects[ding_toggle_format][download][type] = "git"
projects[ding_toggle_format][download][url] = "git@github.com:ding2/ding_toggle_format.git"
projects[ding_toggle_format][download][branch] = "master"

projects[ting_covers][type] = "module"
projects[ting_covers][download][type] = "git"
projects[ting_covers][download][url] = "git@github.com:ding2/ting_covers.git"
projects[ting_covers][download][branch] = "master"

projects[ting_proxy][type] = "module"
projects[ting_proxy][download][type] = "git"
projects[ting_proxy][download][url] = "git@github.com:ding2/ting_proxy.git"
projects[ting_proxy][download][branch] = "master"

projects[ting_infomedia][type] = "module"
projects[ting_infomedia][download][type] = "git"
projects[ting_infomedia][download][url] = "git@github.com:ding2/ting_infomedia.git"
projects[ting_infomedia][download][branch] = "master"

projects[ting_fulltext][type] = "module"
projects[ting_fulltext][download][type] = "git"
projects[ting_fulltext][download][url] = "git@github.com:ding2/ting_fulltext.git"
projects[ting_fulltext][download][branch] = "master"

projects[ting_sfx][type] = "module"
projects[ting_sfx][download][type] = "git"
projects[ting_sfx][download][url] = "git@github.com:ding2/ting_sfx.git"
projects[ting_sfx][download][branch] = "master"

projects[ting_reference][type] = "module"
projects[ting_reference][download][type] = "git"
projects[ting_reference][download][url] = "git@github.com:ding2/ting_reference.git"
projects[ting_reference][branch] = "master"

projects[ting_material_details][type] = "module"
projects[ting_material_details][download][type] = "git"
projects[ting_material_details][download][url] = "git@github.com:ding2/ting_material_details.git"
projects[ting_material_details][download][branch] = "master"

projects[ting_new_materials][type] = "module"
projects[ting_new_materials][download][type] = "git"
projects[ting_new_materials][download][url] = "git@github.com:ding2/ting_new_materials.git"
projects[ting_new_materials][download][branch] = "master"

projects[ting][type] = "module"
projects[ting][download][type] = "git"
projects[ting][download][url] = "git@github.com:ding2/ting.git"
projects[ting][download][branch] = "master"

