<?php
/**
 * Type
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DDB Cover Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Type Class Doc Comment
 *
 * @category Class
 * @description An identifier URI consisting of identifier type as scheme (\&quot;isbn\&quot;, \&quot;faust\&quot;, \&quot;pid\&quot;, \&quot;issn\&quot;,  or \&quot;issn-vol-nr\&quot;) and the identifier itself. **Notice:** A cover can be known under more than one type/ID.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Type
{
    /**
     * Possible values of this enum
     */
    const FAUST = 'faust';
    const ISBN = 'isbn';
    const ISSN = 'issn';
    const ISSN_VOL_NR = 'issn-vol-nr';
    const PID = 'pid';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FAUST,
            self::ISBN,
            self::ISSN,
            self::ISSN_VOL_NR,
            self::PID,
        ];
    }
}


