<?php

/**
 * @file
 * Ding user handling module.
 */

include_once 'ding_user_comments.inc';

/**
 * Implements hook_pathauto_alias_alter().
 *
 * Ensures that provider user don't have aliases create for their accounts.
 */
function ding_user_pathauto_alias_alter(&$alias, $context) {
  if ($context['module'] == 'user') {
    $user = reset($context['data']);
    // The function ding_user_is_provider_user can not be used here. Because if
    // the user is logging in for the first time the "authmap" table have not
    // been populated when this alias function is called.
    if (in_array('provider', $user->roles)) {
      $alias = '';
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function ding_user_preprocess_html(&$variables) {
  $args = arg();
  if ($args[0] == 'user') {
    // Set default title.
    drupal_set_title('Account');

    // Check if current user is logged in.
    if (user_is_logged_in()) {
      // Cache control for user pages.
      drupal_add_http_header('Cache-Control', 'no-store, must-revalidate');
      drupal_add_http_header('Pragma', 'no-cache');
    }
    elseif (count($args) == 1 || isset($args[1]) && in_array($args[1], array('login', 'password'))) {
      // Redirect anonymous user to front page login. This is to prevent the
      // library user from seeing /user, login and password page. Unless in
      // maintenance_mode, there's no front page login when in maintenance_mode,
      // and a redirect prevent login.
      if (!variable_get('maintenance_mode', 0)) {
        if (module_exists('ding_user_form')) {
          // If user forms are enabled goto the login dropdown.
          drupal_goto('', array('fragment' => 'login'));
        }
      }
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * ctools_plugin_example/panels are used.
 */
function ding_user_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_ctools_plugin_api().
 *
 * If you do this, CTools will pick up default panels pages in
 * ding_user.pages_default.inc.
 */
function ding_user_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_menu().
 */
function ding_user_menu() {
  $items = array();

  $items['ding_user/expire_sessions/cron'] = array(
    'title' => 'Lightweight expire session cron',
    'description' => 'Run the lightweight expire inacitve provider sessions cron job',
    'page callback' => '_ding_user_expire_sessions_cron',
    'access callback' => '_ding_user_expire_sessions_cron_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ding_user_permission() {
  return array(
    'administer user settings' => array(
      'title' => t('Administer user settings'),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function ding_user_menu_alter(&$items) {
  // Hook in authentication handling to the regular user edit page.
  // But don't if page_manager overrides it.
  if (!module_exists('page_manager') || variable_get('page_manager_user_edit_disabled', TRUE)) {
    if (isset($items['user/%user/edit']) && $items['user/%user/edit']['page callback'] == 'drupal_get_form') {
      // @TODO: Are there any sites not running panels and will this work with
      // profile2 ?
      $items['user/%user/edit']['page callback'] = 'ding_provider_get_form';
    }
  }

  $items['user/%user/view']['title'] = t('My account');
  $items['user/%user/edit']['title'] = t('User profile');
  $items['user/%pm_arg/status']['title'] = t('User status');

  // Limit access to provider users page.
  $items['user/%user/view']['access callback'] = 'ding_user_provider_user_access';
  $items['user/%user/view']['access arguments'] = array(1);
  $items['user/%user']['access callback'] = 'ding_user_provider_user_access';
  $items['user/%user']['access arguments'] = array(1);

  $items['user']['delivery callback'] = 'ding_user_deliver_html_page';
}

/**
 * Authenticate external user (provider user) and/or create drupal account.
 *
 * If the user info 'pass' key is not defined the provider will try to use the
 * global pass used for single sign on.
 *
 * @param array $user_info
 *   Array keyed by 'name', 'pass' and 'extra.
 *
 * @return bool|object
 *   An drupal user account object or FALSE on failure.
 *
 * @throws Exception|DingProviderUserAuthFailure
 *   Thrown when authentication fails.
 */
function ding_user_authenticate(array $user_info) {
  // Default to FALSE as this is also the default from drupal login.
  $account = FALSE;

  try {
    if (!array_key_exists('pass', $user_info)) {
      // No password provided by the authentication request (not even the empty
      // string), so we assume that this is a single-sign-on request.
      $auth_res = ding_provider_invoke('auth', 'single_sign_on', $user_info['name']);

      // Store value in session to be used later on to check if user was signed
      // in with SSO.
      $_SESSION['ding_user_sso'] = TRUE;
    }
    else {
      // Normal user log in request.
      $auth_res = ding_provider_invoke('user', 'authenticate', $user_info['name'], $user_info['pass'], $sso);
    }
  }
  catch (DingProviderNoProvider $exception) {
    drupal_set_message($exception->getMessage(), 'warning');
    return FALSE;
  }
  if (!is_array($auth_res)) {
    watchdog('ding_user', 'Provider returned invalid result: @res', array('@res' => print_r($auth_res, TRUE)), WATCHDOG_DEBUG);
    return FALSE;
  }

  if ($auth_res['success']) {
    if (isset($auth_res['authname']) && !empty($auth_res['authname'])) {
      // If provider supplied an authentication name, use it.
      $auth_name = $auth_res['authname'];
    }
    else {
      // Else use a standard authentication name.
      $auth_name = ding_user_default_authname($user_info['name']);
    }

    // Create new account in Drupal and if one exists update it.
    $account = _ding_user_create_account($auth_name, $auth_res);

    // Check that a profile exists for the user and if not create one.
    _ding_user_create_profile2($account);

    if ($account->data['blocks']) {
      foreach ($account->data['blocks'] as $block_code) {
        drupal_set_message(ding_user_block_reason($block_code), 'warning');
      }
    }
  }
  else {
    // Check if any messages was returned from the provider.
    if (isset($auth_res['messages'])) {
      foreach ($auth_res['messages'] as $message) {
        $type = 'warning';
        if (is_array($message)) {
          list($message, $type) = $message;
        }
        drupal_set_message(check_plain($message), $type);
      }
    }

    drupal_set_message(t('Sorry but the current library do not have you as an user.'));
  }

  return $account;
}

/**
 * Get user redirect destination.
 *
 * Mainly used by single sign on login to handle redirect after redirect to
 * the SSO service provider.
 *
 * @return string|null
 *   The destination as an URI set in the session or NULL if non is set.
 */
function ding_user_get_destination() {
  return isset($_SESSION['ding_user_destination']) ? $_SESSION['ding_user_destination'] : NULL;
}

/**
 * Set user redirect destination.
 *
 * Mainly used by single sign on login to handle redirect after redirect to
 * the SSO service provider.
 *
 * @param string $destination
 *   The destination to set in the session, normally an URI.
 */
function ding_user_set_destination($destination) {
  $_SESSION['ding_user_destination'] = $destination;
}

/**
 * Implements hook_page_manager_contexts_alter().
 *
 * This is actually a Panels everywhere hook. In future it may be renamed:
 * hook_panels_everywhere_contexts_alter()
 *
 * Panels everywhere puts a extra form tag around the whole page on some pages.
 * This is wrong because there already is a form tag which creates an illegal
 * html markup with nested form tag.
 *
 * This happens because Panels Everywhere reuses code from panels. Because there
 * exist a form in contexts the function function panels_render_display() puts
 * an extra form around the code.
 *
 * The code un-sets the form_id in panels everywhere module order to suppress
 * the superfluous form tag.
 *
 * @See function panels_render_display()
 */
function ding_user_page_manager_contexts_alter(&$contexts, $placeholders) {
  foreach ($contexts as $context) {
    if (!empty($context->form_id)) {
      unset($context->form_id);
    }
  }
}

/**
 * Implements hook_entity_info_alter().
 *
 * Add new view mode used mainly to display the reservation lists in the users
 * profile (not profile2).
 */
function ding_user_entity_info_alter(&$entity_info) {
  $ding_entity_info = ding_entity_info('ding_entity');
  // Entity might not be defined yet (is the case in the installer).
  if (isset($entity_info[$ding_entity_info['entity_type']]['view modes'])) {
    // Add a user_list display mode for add-on modules to use.
    $entity_info[$ding_entity_info['entity_type']]['view modes'] += array(
      'user_list' => array(
        'label' => t('User lists'),
        'custom settings' => TRUE,
      ),
    );
  }
}

/**
 * Page deliver callback.
 *
 * Disables a "page not found" when trying to access provider user account that
 * results in a page denied. This is to prevent enclosing information about the
 * existent of a given user account.
 */
function ding_user_deliver_html_page($page_callback_result) {
  if ($page_callback_result == MENU_ACCESS_DENIED) {
    drupal_deliver_page(MENU_NOT_FOUND);
  }
  else {
    drupal_deliver_html_page($page_callback_result);
  }
}

/**
 * Access callback.
 *
 * Allow access if it's a provider account and the user logged in owns the
 * account or is admin user.
 */
function ding_user_provider_user_access($account) {
  global $user;
  if (ding_user_is_provider_user($account)) {
    if (user_is_logged_in() && !ding_user_is_provider_user($user, TRUE)) {
      return TRUE;
    }

    return ding_user_access($account);
  }

  // Check that the account tried to access is an staff account, if not don't
  // show it.
  return in_array('staff', $account->roles) == FALSE ? ding_user_access($account) : TRUE;
}

/**
 * Access callback.
 *
 * Allows access if the account is the same as the logged in user.
 */
function ding_user_access($account) {
  return ($GLOBALS['user']->uid == $account->uid) && user_is_logged_in();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add setting for pin code length under admin/config/people/accounts, which
 * defaults to 4 as most libraries uses that length.
 *
 * Also add option to set session expire time.
 */
function ding_user_form_user_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['ding_user'] = array(
    '#type' => 'fieldset',
    '#title' => t('Provider user settings'),
    '#weight' => -1,
    '#tree' => FALSE,
  );

  $form['ding_user']['ding_user_pincode_length'] = array(
    '#type' => 'textfield',
    '#title' => t('Pin code length'),
    '#default_value' => ding_user_get_pincode_length(),
    '#description' => t('The required length of the pin code used to access the site. This must be a integer value larger than 0.'),
    '#element_validate' => array('element_validate_integer_positive'),
  );

  // Blocked user information page.
  $form['ding_user']['ding_user_blocked_user_node'] = array(
    '#type' => 'textfield',
    '#title' => t('Link to blocked page'),
    '#default_value' => variable_get('ding_user_blocked_user_node', variable_get('site_404', 'customerror/404')),
    '#description' => t("Link to the node containing explanation about the library's blocked user policies."),
  );

  // Fee for SMS.
  $form['ding_user']['ding_user_fee_sms'] = array(
    '#type' => 'textfield',
    '#title' => t('Fee for SMS'),
    '#default_value' => variable_get('ding_user_fee_sms', t('Notice that there is a fee for receiving a SMS')),
    '#description' => t('Description to show user if a fee for SMS is defined.'),
  );
}

/**
 * Helper function to get the pin-code length from the administration UI.
 *
 * @return int
 *   The length of the pin-code, if not set it will return 4.
 */
function ding_user_get_pincode_length() {
  return variable_get('ding_user_pincode_length', 4);
}

/**
 * Form element validation handler for pincode elements.
 */
function ding_user_element_validate_pincode($element, &$form_state, $form) {
  $pincode_length = ding_user_get_pincode_length();
  $pincode = $element['#value'];
  if (!empty($pincode) && !preg_match('/^\d{' . $pincode_length . '}$/', $pincode)) {
    form_error($element, t('The pincode must consist of exactly %number digits and only contain integers.', array('%number' => $pincode_length)));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add pin-code fields to the provider profile(s), so the users can change their
 * library pin-code.
 */
function ding_user_form_profile2_form_alter(&$form, &$form_state) {
  global $user;
  if (ding_user_is_provider_user($user)) {
    // Check that it's the provider profile we are looking at.
    $profile_type = ding_user_get_provider_profile_type();
    if ($form_state['profile2']->type == $profile_type->type) {
      // Add pin-code change field.
      $maxlength = ding_user_get_pincode_length();
      $form['pass'] = array(
        '#type' => 'fieldset',
        '#title' => t('Change pincode'),
      );

      if (ding_user_name() && !ding_user_is_logged_in_with_sso()) {
        $form['pass']['pincode_old'] = array(
          '#type' => 'password',
          '#title' => t('Confirm old pincode'),
          '#size' => $maxlength,
          '#maxlength' => $maxlength,
          '#attributes' => array('class' => array('password-confirm')),
        );
      }

      $form['pass']['pincode'] = array(
        '#type' => 'password_confirm',
        '#size' => $maxlength,
        '#maxlength' => $maxlength,
        '#process' => array(
          'form_process_password_confirm',
          // Not adding user_form_process_password_confirm here, as it only adds
          // the strength checker, which we don't want.
          'ding_user_form_process_password_confirm',
        ),
        '#description' => t('To change the current pincode, enter the new pincode in both fields.'),
      );

      // Add submit handler to change the pin-code as it's not part of the
      // profile fields.
      $form['#submit'][] = 'ding_user_profile_update_submit';
    }

    $int_per = variable_get('ding_reservation_disable_interest_date', '');
    $profile_provider = 'profile_' . $profile_type->type;
    $field = 'field_' . $profile_type->module . '_interest_period';

    if (!empty($int_per)) {
      $form[$profile_provider][$field]['#access'] = FALSE;
    }
  }

  $form['#validate'][] = 'ding_user_profile_update_validate';
}

/**
 * Password confirm element process.
 *
 * Add in handling of #maxlength and change the titles of the fields.
 */
function ding_user_form_process_password_confirm($element) {
  if (!empty($element['#maxlength'])) {
    $element['pass1']['#maxlength'] = $element['pass2']['#maxlength'] = $element['#maxlength'];
    // Unset #maxlength, or _form_validate will attempt to check the length of
    // this element, whose value will be an array.
    unset($element['#maxlength']);
  }
  unset($element['#maxlength']);

  // Fix-up titles.
  $element['pass1']['#title'] = t('Pincode');
  $element['pass2']['#title'] = t('Confirm pincode');

  // We need to validate length and that it only contains digits. It should be
  // enough to only validate one of the password fields, as they will have to be
  // equal to be accepted.
  $element['pass1']['#element_validate'][] = 'ding_user_element_validate_pincode';

  return $element;
}

/**
 * Validate the user profile form.
 *
 * Check if the old pincode (if present) match the pincode stored in $_SESSION.
 */
function ding_user_profile_update_validate($form, &$form_state) {
  if (isset($form_state['values']['pincode_old'])) {
    if (!empty($form_state['values']['pincode'])) {
      if (empty($form_state['values']['pincode_old'])) {
        form_set_error('pincode_old', t('The old pincode confirm is empty.'));
        return;
      }

      // Check the old pincode with the provider.
      try {
        $auth_res = ding_provider_invoke('user', 'authenticate', ding_user_name(), $form_state['values']['pincode_old']);
      }
      catch (DingProviderUserAuthFailure $e) {
        form_set_error('pincode_old', t('The old pincode confirm does not match.'));
      }
    }
  }
}

/**
 * Updates the users pin-code as part of the profile update.
 *
 * It's done in this submit function as the pin-code is not part of provider
 * profile and this ensures that it never in any way get stored in the DB.
 *
 * Furthermore the pin-code fields are injected into the profile form in the
 * form alter above as there is not password field available, that would not
 * store it in the database.
 */
function ding_user_profile_update_submit(&$form, &$form_state) {
  $pincode = isset($form_state['values']['pincode']) ? $form_state['values']['pincode'] : '';
  // If pin-code is not empty, it's changed.
  if (!empty($pincode)) {
    global $user;
    try {
      $update_res = ding_provider_invoke('user', 'update_pincode', $user, $pincode);
      if (!empty($update_res['creds'])) {
        // Updated drupal credentials.
        ding_user_save_creds($update_res);
      }
    }
    catch (Exception $exception) {
      // If update_account fails, we're in trouble, as we're too far in to
      // set form errors. So we'll just tell the user that it couldn't be, and
      // not save the fields.
      drupal_set_message(t("There was a problem communicating with library system. Please contact the site administrator."), 'error');
      watchdog_exception('ding_user', $exception);
      drupal_set_message(t("New pincode not saved."), 'error');
    }
  }
}

/**
 * Get the provider profile for the given user.
 *
 * @param object $account
 *   Drupal user account object.
 *
 * @return entity|NULL
 *   The profile entity provided by the current provider if any.
 */
function ding_user_provider_profile($account) {
  $profile_type = ding_user_get_provider_profile_type();
  $profile2 = profile2_load_by_user($account, $profile_type->type);
  return is_array($profile2) ? NULL : $profile2;
}

/**
 * Get current provider profile type entity.
 *
 * @todo: Implement hook in the providers that returns the name.
 *
 * @return ProfileType|bool
 *   The profile type entity or FALSE if not found.
 */
function ding_user_get_provider_profile_type() {
  // Get current provider.
  $provider = _ding_provider_get_provider('user');

  // Load provider profile type.
  /* @var ProfileType|FALSE $profile_type */
  $profile_type = profile2_type_load('provider_' . $provider['module']);

  // Return the profile type entity.
  return $profile_type;
}

/**
 * Implements hook_username_alter().
 *
 * @TODO: This do not work with the display name moved into the profile2
 *        provider profile. Maybe change it to use real name module ?
 *        Look at ding_user_update_user().
 *
 * @TODO: This is called 6-7 times on the admin edit user page ?
 *
 * Use display_name.
 */
function ding_user_username_alter(&$name, $account) {
  if (isset($account->data)) {
    if (is_string($account->data)) {
      $data = unserialize($account->data);
    }
    else {
      $data = $account->data;
    }

    if (!empty($data) && isset($data['display_name'])) {
      $name = $data['display_name'];
    }
  }
}

/**
 * Implements hook_ding_provider_user().
 */
function ding_user_ding_provider_user() {
  return array(
    'user' => array(
      'required' => TRUE,
      'install time setup' => TRUE,
    ),
  );
}

/**
 * Return a local hash for the given name.
 *
 * As logins may be CPR numbers, which is really sensitive information, we use
 * a hash of the name and the Drupal private key as authname.
 */
function ding_user_default_authname($name) {
  // If another password.inc is in use, that doesn't define
  // _password_base64_encode(), we'll fail horribly. We'll probably need to
  // define our own base64 function, but we'll cross that bridge when we reach
  // it.
  require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');

  // A sha512 is 64 bytes, which becomes 128 hexadecimal chars, which is
  // exactly the size of the authname field in the database. So we ask hash
  // for binary data and lets _password_base64_encode base64 encode it to 86
  // characters, leaving enough room for our suffix.
  $hash = hash('sha512', ding_user_get_private_key() . $name, TRUE);

  // The string length of the hash have been changed in the line below and we
  // need to update the accounts with new hash values, hence this function call.
  _ding_user_update_old_accounts($hash);
  return _password_base64_encode($hash, drupal_strlen($hash)) . '@ding_user';
}

/**
 * Private key variable used to generate tokens.
 *
 * Apparently the key generated in drupal_get_private_key() may change,
 * so we'll get it from 'ding_user_private_key' variable instead.
 * Preferably set the 'ding_user_private_key' variable in local.settings.php
 *
 * @see https://www.drupal.org/node/487366
 *
 * @return string
 *   The private key.
 *
 * @throws Exception
 *   If private key is not found.
 */
function ding_user_get_private_key() {
  if ($key = variable_get('ding_user_private_key', 0)) {
    return $key;
  }
  watchdog(
    'ding_user',
    'ding_user_private_key not found',
    array(),
    WATCHDOG_CRITICAL
  );
  throw new Exception(t('ding_user_private_key not found'));
}

/**
 * This method updates the user authname hash.
 *
 * It will become deprecated after a while.
 *
 * @param string $hash
 *   Hash used as provider users authname.
 */
function _ding_user_update_old_accounts($hash) {
  // Create authname hash using old workflow (the difference is in strlen VS
  // drupal_strlen).
  $auth_name_old = _password_base64_encode($hash, strlen($hash)) . '@ding_user';

  // Try to find the users uid based on the old hash value (length of the old
  // hash should be 96).
  $uid = db_select('authmap', 'a')
    ->fields('a', array('uid'))
    ->condition('authname', $auth_name_old)
    ->execute()
    ->fetchField();

  // Proceed only in the case it exists and needs to be updated.
  if ($uid) {
    // Create new hash.
    $auth_name_new = _password_base64_encode($hash, drupal_strlen($hash)) . '@ding_user';
    $account_new = user_external_load($auth_name_new);

    // Update old account (authmap and init) only when there is no new account
    // for the same user.
    if (!$account_new) {
      db_update('authmap')
        ->fields(array(
          'authname' => $auth_name_new,
        ))
        ->condition('authname', $auth_name_old)
        ->execute();

      db_update('users')
        ->fields(array(
          'init' => $auth_name_new,
        ))
        ->condition('uid', $uid)
        ->execute();
    }
    // @todo Should the old account be deleted when the user already has a new
    // account?
  }
}

/**
 * Create a provider account for drupal.
 *
 * The username will be a hash value of authname. This account will be coupled
 * with the provider user via the authmap table.
 *
 * @param string $auth_name
 *   Name used to authenticate the user.
 * @param array $auth_res
 *   Authentication information from the provider.
 *
 * @return object
 *   Drupal user object.
 *
 * @throws Exception
 *   If user_save fails exception is thrown.
 */
function _ding_user_create_account($auth_name, array $auth_res) {
  // We'd like to use user_external_login_register(), but it saves the user
  // and invokes hook_user_login before we have a chance to mess with it. So
  // we do what it would do.
  $account = user_external_load($auth_name);

  $mail = NULL;
  $display_name = '';
  $blocks = FALSE;
  if (isset($auth_res['user'])) {
    if (isset($auth_res['user']['mail'])) {
      $mail = $auth_res['user']['mail'];
    }

    if (isset($auth_res['user']['data']['display_name'])) {
      $display_name = $auth_res['user']['data']['display_name'];
    }

    if (!empty($auth_res['user']['blocks'])) {
      $blocks = array_unique($auth_res['user']['blocks']);
    }
  }

  if (!$account) {
    // Register this new user.
    $fields = array(
      // Name is only 60 chars, and authname is longer. Use a shorter SHA1
      // hash.
      'name' => hash('sha1', $auth_name),
      'pass' => user_password(),
      'init' => $auth_name,
      'status' => 1,
      'access' => REQUEST_TIME,
      'mail' => '',
    );

    if ($mail) {
      $fields['mail'] = $mail;
    }
    $fields['data'] = array(
      'display_name' => $display_name,
      'blocks' => $blocks,
    );

    // Set provider role.
    $roles = user_roles(TRUE);
    $rid = array_search('provider', $roles);
    $fields['roles'] = array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
      $rid => 'provider',
    );

    $account = user_save('', $fields);
    // Terminate if an error occurred during user_save().
    if (!$account) {
      watchdog('ding_user', "User account could not be created for: %name.", array('%name' => $auth_res['user']['data']['display_name']), WATCHDOG_ERROR);
      drupal_set_message(t("Error saving user account."), 'error');
      return NULL;
    }
    user_set_authmaps($account, array("authname_ding_user" => $auth_name));
  }
  else {
    // Update display name and mail address as they may have been change in the
    // library system.
    $edit = array();
    if ($mail) {
      $edit['mail'] = $mail;
    }
    $edit['data'] = array(
      'display_name' => $display_name,
      'blocks' => $blocks,
    );
    user_save($account, $edit);
  }

  // Save credentials for the session.
  ding_user_save_creds($auth_res);

  return $account;
}

/**
 * Create a profile2 provider profile for the account, if one do not exists.
 *
 * @param object $account
 *   Drupal user account object.
 *
 * @return object
 *   The newly create profile entity or the existing one.
 */
function _ding_user_create_profile2($account) {
  $profile = ding_user_provider_profile($account);
  if (!$profile) {
    // Load profile2 type.
    $profile_type = ding_user_get_provider_profile_type();

    // Create a profile for current user.
    $profile = new Profile(array(
      'user' => $account,
      'type' => $profile_type,
    ));

    // Bind this profile to the user.
    $profile->save();
  }
  return $profile;
}

/**
 * Implements hook_forms().
 *
 * Enables the profile2 form panels pane to generate a form for a profile2
 * entity. The code is largely taken from the profile2 page module, but we only
 * need this part of the module.
 */
function ding_user_forms($form_id, $args) {
  // For efficiency, only act if the third argument is 'profile2'.
  if (isset($args[2]) && is_string($args[2]) && $args[2] == 'profile2') {
    // Reuse profile2 page extension code.
    include_once drupal_get_path('module', 'profile2') . '/contrib/profile2_page.inc';

    $info = entity_get_info('profile2');
    // Translate bundle form ids to the base form id 'profile2_form'.
    $forms = array();
    foreach ($info['bundles'] as $bundle => $bundle_info) {
      $forms['profile2_edit_' . $bundle . '_form']['callback'] = 'profile2_form';
      $forms['profile2_edit_' . $bundle . '_form']['wrapper callback'] = 'entity_ui_form_defaults';
    }
    return $forms;
  }
}

/**
 * Ajax command to authenticate.
 *
 * @param mixed $extra_data
 *   Options to send to ding_popup.
 * @param string $redirect_uri
 *   Destination to redirect to after login is completed.
 *
 * @return array
 *   Ajax command array.
 */
function ajax_command_ding_user_authenticate($extra_data, $redirect_uri = '') {
  $hook = 'ajax_login_command';
  $modules = module_implements($hook);
  if (count($modules) > 0) {
    if (empty($redirect_uri)) {
      $url = parse_url($_SERVER['HTTP_REFERER']);
      $path_start = strpos($_SERVER['HTTP_REFERER'], '/', drupal_strlen($url['scheme']) + 3);
      $referer = drupal_substr($_SERVER['HTTP_REFERER'], $path_start + 1);
      $redirect_uri = empty($referer) ? '/' : urldecode($referer);
    }

    foreach ($modules as $module) {
      $command = module_invoke($module, $hook, $redirect_uri);
    }
  }
  else {
    // Change default ajax action to default login form's if https is enabled.
    if (variable_get('https', FALSE)) {
      $form = drupal_get_form('user_login');
      $url = parse_url($_SERVER['HTTP_REFERER']);
      $path_start = strpos($_SERVER['HTTP_REFERER'], '/', drupal_strlen($url['scheme']) + 3);
      $referer = drupal_substr($_SERVER['HTTP_REFERER'], $path_start + 1);

      $form['#action'] = 'https://' . $_SERVER['SERVER_NAME'] . url('user/login') . '?destination=' . $referer;
    }
    else {
      $form_state = array();
      $form = drupal_build_form('user_login', $form_state);
    }

    $login_form = drupal_render($form);
    $command = ajax_command_ding_popup('ding_user', t('Login'), $login_form, array('resubmit' => TRUE, 'extra_data' => $extra_data));
  }

  return $command;
}

/**
 * Retrieves the users credentials from the current session.
 *
 * @return array
 *   Array with the user credentials.
 *
 * @throws DingProviderAuthException
 *   Throws DingProviderAuthException if not authenticated.
 */
function ding_user_get_creds() {
  if (isset($_SESSION['ding_user'])) {
    // User has not timed out by auto logout module so return credentials.
    return $_SESSION['ding_user']['creds'];
  }

  throw new DingProviderAuthException();
}

/**
 * Store user credentials in the current session.
 *
 * @param array $auth_res
 *   Array with authentication information used to communicate with the
 *   provider.
 */
function ding_user_save_creds(array $auth_res) {
  if (isset($auth_res['creds'])) {
    $_SESSION['ding_user'] = $auth_res;
  }
}

/**
 * Get a unique id from the provider.
 *
 * @param object $account
 *   User account to get id for. Defaults to NULL which then results in the
 *   currently logged in user.
 *
 * @return mixed|null
 *   The id or NULL if provider don't support it.
 *
 * @throws DingProviderDoesntImplement
 *   If the provider do not implement the "get_provider_id" call.
 * @throws DingProviderNoProvider
 *   If the current provider don't supports the "get_provider_id" call.
 */
function ding_user_provider_id($account = NULL) {
  global $user;

  if ($account === NULL) {
    $account = $user;
  }

  if (ding_provider_implements('user', 'get_provider_id')) {
    return ding_provider_invoke('user', 'get_provider_id', $account);
  }

  return NULL;
}

/**
 * Returns user login name of the current user, if available.
 *
 * Checks if provider has a get_name function, or has set name in creds.
 */
function ding_user_name() {
  global $user;
  try {
    if (ding_provider_implements('user', 'get_name')) {
      return ding_provider_invoke('user', 'get_name', $user);
    }
    $creds = ding_user_get_creds();
    if (isset($creds['name'])) {
      return $creds['name'];
    }
  }
  catch (Exception $e) {
    // Do nothing.
  }

  return NULL;
}

/**
 * Check if the given account is a user authenticated through a provider.
 *
 * @param object $account
 *   The user account to check.
 * @param bool $reset
 *   If TRUE static cache is ignored else FALSE. Default FALSE.
 *
 * @return bool
 *   TRUE if account is a provider account else FALSE.
 */
function ding_user_is_provider_user($account, $reset = FALSE) {
  // If someone calls us on a new user object before it's saved, we have no
  // idea, so return false.
  if (!isset($account->uid)) {
    return FALSE;
  }
  if (!$reset) {
    $names = &drupal_static(__FUNCTION__);
  }
  if (!isset($names)) {
    $names = db_select('authmap')
      ->fields('authmap', array('authname'))
      ->condition('module', 'ding_user')
      ->condition('uid', $account->uid)
      ->execute()->fetchAll();
  }

  return !empty($names);
}

/**
 * Check if user was singed in using single-sign-on.
 *
 * @return bool
 *   If logged in with SSO TRUE else FALSE.
 */
function ding_user_is_logged_in_with_sso() {
  return isset($_SESSION['ding_user_sso']) ? $_SESSION['ding_user_sso'] : FALSE;
}

/**
 * Implements hook_comment_load().
 *
 * Use actual user name (display_name) instead of the hash values for provider
 * users.
 */
function ding_user_comment_load($comments) {
  $user_names = array();

  // Get comment authors user id (uid).
  $uids = array();
  foreach ($comments as $comment) {
    if ($comment->uid == 0) {
      continue;
    }
    $uids[] = $comment->uid;
  }
  $uids = array_unique($uids);
  // Map uid => key.
  $uids_rev = array_flip($uids);

  // Get user names from cache.
  $cids = array_map('_ding_user_comment_cache_id', $uids);
  $caches = cache_get_multiple($cids);
  foreach ($caches as $cache) {
    $data = $cache->data;
    $user_names[$data[0]] = $data[1];

    // User found in cache, so remove him/her form the lists of missing user
    // names.
    unset($uids[$uids_rev[$data[0]]]);
  }

  // Try to get names from the database for those not found in the cache..
  if (!empty($uids)) {
    $data = db_select('users', 'u')
      ->fields('u', array('uid', 'data'))
      ->isNotNull('u.data')
      ->condition('u.uid', $uids)
      ->execute()
      ->fetchAll(PDO::FETCH_ASSOC);

    foreach ($data as $row) {
      $user_data = unserialize($row['data']);
      if (empty($user_data['display_name'])) {
        // Display name was not found for the user.
        $data = array($row['uid'], NULL);
      }
      else {
        // Display name found.
        $data = array($row['uid'], $user_data['display_name']);
      }

      // Store the user names in cache for faster look-ups.
      cache_set(_ding_user_comment_cache_id($row['uid']), $data);
      $user_names[$data[0]] = $data[1];
    }
  }

  // Set proper user names.
  foreach ($comments as $comment) {
    if (empty($user_names[$comment->uid])) {
      continue;
    }
    $comment->name = $user_names[$comment->uid];
  }
}

/**
 * Implements hook_FROM_ID_alter().
 *
 * Alters the site wide contact form to allow all users to send a copy to them
 * self.
 */
function ding_user_form_contact_site_form_alter(&$form, $form_state, $form_id) {
  $form['copy']['#access'] = TRUE;
}

/**
 * Get cache id by uid.
 *
 * @param int $uid
 *   Comment author uid.
 *
 * @return string
 *   Cache ID.
 */
function _ding_user_comment_cache_id($uid) {
  return 'ding_user_comment_user_name:' . $uid;
}

/**
 * Implements hook_profile2_view().
 */
function ding_user_profile2_view($profile, $view_mode, $langcode) {
  $provider = _ding_provider_get_provider('user');
  $field = 'field_' . $provider['module'] . '_interest_period';

  $field_items = field_get_items('profile2', $profile, $field);

  if ($field_items) {
    $int_per = variable_get('ding_reservation_disable_interest_date', '');

    if ($int_per == 1) {
      $profile->content[$field]['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function ding_user_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form':
      global $user;
      if (user_access('administer users') && !in_array('administrators', $user->roles)) {
        $form['#validate'][] = '_ding_user_roles_form_validate';
      }
      break;
  }
}

/**
 * Check if newly created user has assigned new roles.
 *
 * @param array $form
 *   Register form elements.
 * @param array $form_state
 *   State of the submitted form.
 */
function _ding_user_roles_form_validate(array $form, array &$form_state) {
  if (!array_filter($form_state['values']['roles_change'])) {
    form_set_error('roles', t('Roles field is required.'));
  }
}

/**
 * Returns the message for the "block" type.
 */
function ding_user_block_reason($type) {
  $reasons = &drupal_static(__FUNCTION__);
  if (empty($reasons)) {
    $reasons = module_invoke_all('ding_user_block_reasons');
    // Fallback message.
    $reasons['default'] = t('Your account is limited. Please contact your library for more information.');
  }

  if (!isset($reasons[$type])) {
    $type = 'default';
  }

  return $reasons[$type];
}

/**
 * Implements hook_ding_user_block_reasons().
 */
function ding_user_ding_user_block_reasons() {
  return array(
    'ding_user_blocked_debt' => t('Your account is limited due to outstanding debt. Please contact your library for more information.'),
    'ding_user_blocked_self_created' => t('Your self created account is limited. Please contact your library to get full access.'),
    'ding_user_blocked_excluded' => t('You have been excluded. Please contact your library for more information.'),
  );
}

/**
 * Implements hook_cron()
 */
function ding_user_cron() {
  _ding_user_expire_sessions();
}

/**
 *	Access callback for expires sessions cron endpoint.
 */
function _ding_user_expire_sessions_cron_access($cron_key) {
  return variable_get('cron_key') === $cron_key;
}

/**
 * Page callback for expires sessions lightweight cron endpoint.
 */
function _ding_user_expire_sessions_cron() {
  _ding_user_expire_sessions();
  drupal_exit();
}

/**
 * Deletes inactive provider sessions in the database.
 */
function _ding_user_expire_sessions() {
  if (!$limit = variable_get('ding_user_provider_session_expire', 900)) {
    // Return now if the session expire functionality is disabled.
    return;
  }

  // Delete sessions with no activity since $limit seconds.
  $timestamp = REQUEST_TIME - $limit;

  // Construct subquere with uids for provider users.
  $roles = user_roles(TRUE);
  $rid = array_search('provider', $roles);
  $subquery = db_select('users_roles', 'ur')
    ->fields('ur', array('uid'))
    ->condition('rid', $rid);

  $query = db_delete('sessions')
    ->condition('timestamp', $timestamp, '<')
    ->condition('uid', $subquery, 'IN');

  $num_updated = $query->execute();

  // Log a notice if we succesfully deleted any inacitve provider sessions.
  if ($num_updated) {
    watchdog('ding_user', 'Deleted %num_updated inactive provider sessions', array(
      '%num_updated' => $num_updated,
    ));
  }
}


