<?php

/**
 * @file
 * Ding SEO module file.
 */

/**
 * Implements hook_metatag_get_entity_metatags_instance_alter().
 *
 * Note: appearently this hook has to reside in module file and can not be in
 * ding_seo.metatag.inc. or else it will ONLY be called on first page load
 * after a cache clear. Investigate why this happens?
 */
function ding_seo_metatag_get_entity_metatags_instance_alter(&$instance, $entity, $entity_type, $bundle) {
  if ($entity_type == 'ting_object') {
    // Use simple material type checking for now to decide a ting objects schema
    // type. We will have to get more complex in the future, when we have to
    // distinguish between movies and tv-series for example. Also if we wish to
    // be provider independant we need a mechanism to avoid hard coded values.
    // For now this is opensearch speficic anb based and DKABM types:
    // http://www.danbib.dk/docs/abm/types.xml
    $material_type = drupal_strtolower($entity->getType());

    $schema_type_mapping = [
      'book' => [
        'bog',
        'bog stor skrift',
        'billedbog',
        'ebog',
        'lydbog (bånd)',
        'lydbog (cd)',
        'lydbog (net)',
        'lydbog (cd-mp3)',
        'årbog',
      ],
      'movie' => [
        'dvd',
        'dvd (film)',
        'blu-ray',
        'film',
        'film (net)',
      ]
    ];

    foreach ($schema_type_mapping as $schema_type => $material_types) {
      if (in_array($material_type, $material_types)) {
        $instance = 'ting_object:' . $schema_type;
        return;
      }
    }
  }
}

/**
 * Determine the schema.org bookFormat for a ting_object.
 *
 * We aim to support the format types supported by Google;
 * https://developers.google.com/search/docs/data-types/book#work-example
 *
 * @param $ting_object
 *   The ting_object to determine book format for.
 *
 * @return mixed
 *   One of the supported book format types as string. NULL if no book format
 *   could be determined for the $ting_object.
 */
function ding_seo_get_schema_book_format($ting_object) {
  $material_type = drupal_strtolower($ting_object->getType());

  $schema_book_format_mapping = [
    'EBook' => [
      'ebog'
    ],
    // TODO: Can differentiaie between Hardcove and Paperback?
    // For now use map all physical books to Hardcover.
    'Paperback' => [],
    'Hardcover' => [
      'bog',
      'bog stor skrift',
      'billedbog',
    ],
    'AudioBook' => [
      'lydbog (bånd)',
      'lydbog (cd)',
      'lydbog (net)',
      'lydbog (cd-mp3)',
    ],
  ];

  foreach ($schema_book_format_mapping as $book_format => $material_types) {
    if (in_array($material_type, $material_types)) {
      return $book_format;
    }
  }
  return NULL;
}
