<?php

/**
 * @file
 * Defines basic campaigns triggers and handling.
 */

define('DING_CAMPAIGN_PLUS_FACET_TYPE', 'facet');

/**
 * Implements hook_ding_campaign_plus_info().
 */
function ding_campaign_plus_facet_ding_campaign_plus_info() {
  return array(
    'title' => t('Facets'),
    'type' => DING_CAMPAIGN_PLUS_FACET_TYPE,
    'form' => 'ding_campaign_plus_facet_admin_form',
    'auto' => 'ding_campaign_plus_facet_auto_admin_form',
    'weight' => 0,
  );
}

/**
 * Implements hook_ding_campaign_plus_default_weights().
 */
function ding_campaign_plus_facet_ding_campaign_plus_default_weights() {
  $facets = _ding_campaign_plus_facet_get_facets();

  $weights = array();
  foreach ($facets as $facet) {
    $weights[$facet['facet']] = array(
      'prefix' => t('Facet'),
      'title' => $facet['title'],
      'weight' => 0,
    );
  }

  return $weights;
}

/**
 * Implements hook_menu().
 */
function ding_campaign_plus_facet_menu() {
  $items = array();
  $items['admin/config/ding/campaigns_plus/%/delete'] = array(
    'title' => 'Delete facets',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_campaign_plus_facet_delete', 4),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ding_campaign_plus_facet_theme($existing, $type, $theme, $path) {
  $themes = array(
    'ding_campaign_plus_facet_table_drag' => array(
      'render element' => 'element'
    ),
  );
  return $themes;
}

/**
 * Implements hook_node_load().
 */
function ding_campaign_plus_facet_node_load($nodes, $types) {
  foreach ($nodes as $node) {
    if ($node->type === 'ding_campaign_plus') {
      $rules = db_select('ding_campaign_plus_facet', 'dcpf')
        ->fields('dcpf')
        ->condition('nid', $node->nid)
        ->execute()
        ->fetchAllAssoc('id');

      foreach ($rules as &$rule) {
        $rule->value = unserialize($rule->value);

        // Add type to easy identify this rule type.
        $rule->type = 'facet';
      }

      if (!isset($node->ding_campaign_plus)) {
        $node->ding_campaign_plus = array();
      }
      $node->ding_campaign_plus = array_merge($node->ding_campaign_plus, $rules);
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function ding_campaign_plus_facet_node_insert($node) {
  if ($node->type === 'ding_campaign_plus') {
    $triggers = $node->tabs[DING_CAMPAIGN_PLUS_FACET_TYPE];

    foreach ($triggers['rules'] as $rule) {
      if (!is_array($rule)) {
        continue;
      }

      switch ($rule['facet']) {
        case 'facet.type':
          $value = $rule['facet_value_select_type'];
          $value = empty($value) ? $value : serialize($value);
          break;

        case 'facet.acSource':
          $value = $rule['facet_value_select_source'];
          $value = empty($value) ? $value : serialize($value);
          break;

        default:
          $value = empty($rule['facet_value']) ? $rule['facet_value'] : serialize($rule['facet_value']);
      }

      if (!empty($value)) {
        db_insert('ding_campaign_plus_facet')
          ->fields(array(
            'nid' => $node->nid,
            'facet' => $rule['facet'],
            'value' => $value,
            'common' => $rule['common'] === '_none_' ? NULL : $rule['common'],
          ))->execute();
      }
    }
  }
}

/**
 * Implements hook_node_update().
 */
function ding_campaign_plus_facet_node_update($node) {
  if ($node->type === 'ding_campaign_plus') {
    ding_campaign_plus_facet_node_delete($node);
    ding_campaign_plus_facet_node_insert($node);
  }
}

/**
 * Implements hook_node_delete().
 */
function ding_campaign_plus_facet_node_delete($node) {
  if ($node->type === 'ding_campaign_plus') {
    db_delete('ding_campaign_plus_facet')
      ->condition('nid', $node->nid)
      ->execute();
  }
}

/**
 * Implements hook_ding_campaign_plus_matches().
 */
function ding_campaign_plus_facet_ding_campaign_plus_matches($contexts, $style) {
  $matches = array();

  foreach ($contexts as $key => $context) {
    switch ($key) {
      case 'search_term':
        $triggers = _ding_campaign_plus_facet_match($context);
        foreach ($triggers as $facet => $nids) {
          $matches[$facet] = $nids;
        }
        break;
    }
  }

  return $matches;
}

/**
 * Build form options used to configure auto generated campaigns.
 *
 * @param array $form_state
 *   The forms current state.
 * @param array $default
 *   The default configuration value.
 *
 * @return array
 *   The form element send into the admin form.
 */
function ding_campaign_plus_facet_auto_admin_form(array &$form_state, $default = array()) {
  $options = array();
  $facets = _ding_campaign_plus_facet_get_facets();
  foreach ($facets as $facet) {
    $options[$facet['facet']] = $facet['title'] . ' (' . $facet['facet'] . ')';
  }

  return array(
    'default' => array(
      '#type' => 'select',
      '#title' => t('Default common number'),
      '#description' => t('Default "Most common subjects" to match against.'),
      '#options' => drupal_map_assoc(range(1, 15)),
      '#default_value' => empty($default['default']) ? '_none_' : $default['default'],
    ),
    'facets' =>  array(
      '#type' => 'radios',
      '#title' => t('Facets available'),
      '#description' => t('The contents subjects will automatically create a trigger against the selected facet type.'),
      '#options' => array('_none_' => t('None')) + $options,
      '#default_value' => empty($default['facets']) ? '_none_' : $default['facets'],
    ),
  );
}

/**
 * Implements hook_form_ding_campaign_plus_admin_settings_alter().
 *
 * Added form elements to the configuration form to define which facets should
 * be available for facet triggers.
 */
function ding_campaign_plus_facet_form_ding_campaign_plus_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['ding_campaign_plus_facets'] = array(
    '#type' => 'fieldset',
    '#title' => 'Facets',
    '#tree' => TRUE,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => 0,
  );

  $form['ding_campaign_plus_facets']['facets'] = array(
    '#prefix' => '<div id="facets">',
    '#suffix' => '</div>',
    '#theme' => 'ding_campaign_plus_facet_table_drag',
  );


  $facets = _ding_campaign_plus_facet_get_facets();
  foreach ($facets as $id => $facet) {
    $form['ding_campaign_plus_facets']['facets'][$id]['facet'] = array(
      '#type' => 'textfield',
      '#title' => t('Facet id'),
      '#title_display' => 'invisible',
      '#default_value' => $facet['facet'],
    );

    $form['ding_campaign_plus_facets']['facets'][$id]['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#title_display' => 'invisible',
      '#default_value' => $facet['title'],
    );

    $form['ding_campaign_plus_facets']['facets'][$id]['weight'] = array(
      '#type' => 'weight',
      '#title' => t('Weight'),
      '#default_value' => $facet['weight'],
      '#title_display' => 'invisible',
      '#attributes' => array('class' => array('facet-weight')),
    );

    $form['ding_campaign_plus_facets']['facets'][$id]['action'] = array(
      '#type' => 'link',
      '#title' => t('delete'),
      '#href' =>  'admin/config/ding/campaigns_plus/' . $facet['facet'] . '/delete',
      '#options' => array('attributes' => array('title' => t('Delete facet.'))),
    );
  }

  $id++;
  $form['ding_campaign_plus_facets']['facets'][$id]['facet'] = array(
    '#type' => 'textfield',
    '#title' => t('Facet id'),
    '#default_value' => '',
  );

  $form['ding_campaign_plus_facets']['facets'][$id]['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => '',
  );

  $form['ding_campaign_plus_facets']['facets'][$id]['weight'] = array(
    '#type' => 'weight',
    '#title' => t('Weight'),
    '#default_value' => 10,
    '#attributes' => array('class' => array('facet-weight')),
  );

  $form += array('#submit' => array());
  $form['#submit'][] = 'ding_campaign_plus_facet_admin_settings_form_submit';
}

/**
 * Submit handler for the administration form.
 */
function ding_campaign_plus_facet_admin_settings_form_submit($form, $form_state) {
  $facets = $form_state['values']['ding_campaign_plus_facets']['facets'];
  foreach ($facets as $id => $facet) {
    if (empty($facet['facet'])) {
      unset($facets[$id]);
    }
  }

  variable_set('ding_campaign_plus_facets', $facets);
}

/**
 * Menu callback for facet delete confirm.
 *
 * @param $form_id
 *   ID of the form calling the delete action.
 * @param $form_state
 *   The state of the form.
 * @param $facet_id
 *   The ID of the facets to remove.
 *
 * @return mixed
 *   Confirmation for.
 */
function ding_campaign_plus_facet_delete($form_id, $form_state, $facet_id) {
  $form['facet_id'] = array(
    '#type' => 'value',
    '#value' => $facet_id,
  );
  return confirm_form($form, t("Are you sure you want to delete @facet?", array('@facet' => $facet_id)), 'admin/config/ding/campaigns_plus');
}

/**
 * Submit handler for the delete facet confirmation form.
 */
function ding_campaign_plus_facet_delete_submit($form, &$form_state) {
  $facets = variable_get('ding_campaign_plus_facets', array());
  foreach ($facets as $key => $facet) {
    if ($facet['facet'] == $form_state['values']['facet_id']) {
      unset($facets[$key]);
    }
  }
  variable_set('ding_campaign_plus_facets', $facets);
  drupal_set_message(t('@facet deleted.', array('@facet' => $form_state['values']['facet_id'])));
  $form_state['redirect'] = 'admin/config/ding/campaigns_plus';
}

/**
 * Default theme function for facet table.
 *
 * Add draggable table layout to facet table.
 *
 * @param array $vars
 *   The variables for this theme function (form element).
 *
 * @return string
 *  The formatted table.
 */
function theme_ding_campaign_plus_facet_table_drag($vars) {
  drupal_add_tabledrag('campaign-facets', 'order', 'sibling', 'facet-weight');

  $rows = array();
  foreach (element_children($vars['element']) as $id) {
    $facet = $vars['element'][$id];
    $row = array();
    $row[] = drupal_render($facet['facet']);
    $row[] = drupal_render($facet['title']);
    $row[] = drupal_render($facet['weight']);
    $row[] = drupal_render($facet['action']);

    $rows[] = array(
      'data' => $row,
      'class' => array('draggable'),
    );
  }

  $header = array(t('Facet'), t('Title'), t('Weight'), t('Operations'));
  return theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('id' => 'campaign-facets'),
  ));
}

/**
 * Implements hook_ding_campaign_plus_auto_trigger().
 *
 * When auto-generating campaigns this defines the triggers for the facet
 * module.
 */
function ding_campaign_plus_facet_ding_campaign_plus_auto_trigger($config, $campaign_node, $node, $subjects) {
  $trigger = array();
  $trigger[DING_CAMPAIGN_PLUS_FACET_TYPE] = array('rules' => array());

  if ($config['facets'] != '_none_' && !empty($subjects)) {
    foreach ($subjects as $key => $value) {
      $trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key] = array(
        'facet' => $config['facets'],
        'common' => NULL,
      );

      switch ($config['facets']) {
        case 'facet.type':
          $options = _ting_fetch_well_types();
          $options = array_keys($options);
          if (in_array($value, $options)) {
            $trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key]['facet_value_select_type'] = $value;
          }
          else {
            unset($trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key]);
          }
          break;

        case 'facet.acSource':
          $options = _ting_fetch_well_sources();
          $options = array_keys($options);
          if (in_array($value, $options)) {
            $trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key]['facet_value_select_source'] = $value;
          }
          else {
            unset($trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key]);
          }
          break;

        case 'facet.subject':
          $trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key]['common'] = $config['default'];
          $trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key]['facet_value'] = $value;
          break;

        default:
          $trigger[DING_CAMPAIGN_PLUS_FACET_TYPE]['rules']['rule_' . $key]['facet_value'] = $value;
          break;
      }
    }
  }

  return $trigger;
}

/**
 * The node edit form callback defined in the hook_ding_campaign_plus_info.
 */
function ding_campaign_plus_facet_admin_form(&$form_state) {
  $values = array();
  if (isset($form_state['values']['tabs'][DING_CAMPAIGN_PLUS_FACET_TYPE]['rules'])) {
    $values = $form_state['values']['tabs'][DING_CAMPAIGN_PLUS_FACET_TYPE]['rules'];
  }

  // Get campaign rule from node.
  if (empty($values) && isset($form_state['node']->ding_campaign_plus)) {
    $values = _ding_campaign_plus_facet_get_rules($form_state['node']->nid, $form_state['node']->ding_campaign_plus);
    $values['count'] = count($values);
  }
  $count = !empty($values['count']) ? $values['count'] : 0;

  // Check if remove button has been pressed. If so remove element from
  // form_state values.
  if (isset($form_state['triggering_element'])) {
    if ($form_state['triggering_element']['#op'] === 'remove' && substr($form_state['triggering_element']['#name'], 0, 18) === 'remove_facet_rule_') {
      $rule = 'rule_' . $form_state['triggering_element']['#rule'];
      unset($values[$rule]);
      unset($form_state['values']['tabs']['facet']['rules'][$rule]);
    }
  }

  $triggers = array(
    '#prefix' => '<div id="ding-campaign-facet-triggers">',
    '#suffix' => '</div>',
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'ding_campaign_plus_facet') . '/js/ding_campaign_plus_facet.admin.js',
      ),
    ),
  );

  // If this form is "add another" or "remove" build rules already form_state
  // values.
  foreach ($values as $key => $value) {
    if (substr($key, 0, 4) === "rule") {
      $triggers[$key] = _ding_campaign_plus_facet_rule_form(substr($key, 5), $value);
    }
  }

  // If not a remove operation add one more element.
  if (!isset($form_state['triggering_element'])) {
    $triggers['rule_' . $count] = _ding_campaign_plus_facet_rule_form($count);
  }
  elseif ($form_state['triggering_element']['#name'] === 'add_another_facet') {
    // Check if it was this sub-form that need another element added if not
    // exit to prevent extra elements being generated.
    $count++;
    $triggers['rule_' . $count] = _ding_campaign_plus_facet_rule_form($count);
  }

  $triggers['count'] = array(
    '#type' => 'hidden',
    '#value' => $count,
  );

  $triggers['add_rule'] = array(
    '#type' => 'button',
    '#name' => 'add_another_facet',
    '#value' => t('Add another'),
    '#ajax' => array(
      'callback' => '_ding_campaign_plus_facet_rule_ajax_callback',
      'wrapper' => 'ding-campaign-facet-triggers',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  return $triggers;
}

/**
 * Return the facet rules part of the form.
 *
 * @param array $form
 *   Form array.
 * @param array $form_state
 *   Form state array.
 *
 * @return array
 *   Form element - rule fields.
 */
function _ding_campaign_plus_facet_rule_ajax_callback(array $form, array $form_state) {
  return $form['triggers']['tabs']['facet']['rules'];
}

/**
 * Rule form fields chunk.
 *
 * @param int $number
 *   The rule number (used for UI numbering).
 * @param array $default_values
 *   The default values for the fields.
 *
 * @return array
 *   Rule fields structure.
 */
function _ding_campaign_plus_facet_rule_form($number = 0, array $default_values = array()) {
  $form = array(
    '#type' => 'fieldset',
    '#title' => t('Rule %num', array('%num' => $number)),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $options = array();
  $facets = _ding_campaign_plus_facet_get_facets();
  foreach ($facets as $facet) {
    $options[$facet['facet']] = $facet['title'];
  }

  $form['facet'] = array(
    '#type' => 'select',
    '#title' => t('Facet Type'),
    '#default_value' => isset($default_values['facet']) ? $default_values['facet'] : 'facet.type',
    '#options' => $options,
    '#attributes' => array(
      'class' => array('js-fact-type'),
    ),
  );

  // Get default "most common" from auto-generate campaign configuration. This
  // is a lose dependency to auto generate module and should stay lose.
  $default = variable_get('ding_campaign_plus_auto', array());
  $default = isset($default['ding_campaign_plus_facet']['config']['default']) ? $default['ding_campaign_plus_facet']['config']['default'] : 5;

  $options = drupal_map_assoc(range(1, 15));
  $form['common'] = array(
    '#type' => 'select',
    '#title' => t('Most common subjects'),
    '#options' => array_combine($options, $options),
    '#default_value' => isset($default_values['common']) ? $default_values['common'] : $default,
  );

  $options = _ting_fetch_well_types();
  $options = array_keys($options);
  $options = array_combine($options, $options);
  $form['facet_value_select_type'] = array(
    '#type' => 'select',
    '#title' => t('Facet'),
    '#default_value' => isset($default_values['facet_value_select_type']) ? $default_values['facet_value_select_type'] : array(),
    '#options' => $options,
    '#multiple' => TRUE,
    '#size' => min(8, count($options)),
  );

  $options = _ting_fetch_well_sources();
  $options = array_keys($options);
  $options = array_combine($options, $options);
  $form['facet_value_select_source'] = array(
    '#type' => 'select',
    '#title' => t('Facet'),
    '#default_value' => isset($default_values['facet_value_select_source']) ? $default_values['facet_value_select_source'] : array(),
    '#options' => $options,
    '#multiple' => TRUE,
    '#size' => min(8, count($options)),
  );

  $form['facet_value'] = array(
    '#type' => 'textfield',
    '#title' => t('Facet value'),
    '#default_value' => isset($default_values['facet_value']) ? $default_values['facet_value'] : '',
    '#size' => 64,
    '#maxlength' => 255,
  );

  $form['remove_rule_' . $number] = array(
    '#type' => 'button',
    '#value' => t('Remove'),
    '#name' => 'remove_facet_rule_' . $number,
    '#op' => 'remove',
    '#rule' => $number,
    '#ajax' => array(
      'callback' => '_ding_campaign_plus_facet_rule_ajax_callback',
      'wrapper' => 'ding-campaign-facet-triggers',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  return $form;
}

/**
 * Find "facet" rules in the current rules for a given node.
 *
 * @param int $nid
 *   Node id for the node (used as index in static cache).
 * @param array $rules
 *   All the rules loaded for the node.
 *
 * @return array
 *   The rules of the basic types.
 */
function _ding_campaign_plus_facet_get_rules($nid, array $rules) {
  $filtered = &drupal_static(__FUNCTION__, array());

  if (!isset($filtered[$nid])) {
    $filtered[$nid] = array();

    foreach ($rules as $rule) {
      if ($rule->type === 'facet') {
        $value_type = array();
        $value_source = array();
        $value = '';

        switch ($rule->facet) {
          case 'facet.type':
            $value_type = $rule->value;
            break;

          case 'facet.acSource':
            $value_source = $rule->value;
            break;

          default:
            $value = $rule->value;
            break;
        }

        $filtered[$nid]['rule_' . count($filtered[$nid])] = array(
          'facet' => $rule->facet,
          'common' => $rule->common,
          'facet_value_select_type' => $value_type,
          'facet_value_select_source' => $value_source,
          'facet_value' => $value,
        );
      }
    }
  }

  return $filtered[$nid];
}

/**
 * Get facets.
 *
 * Default to facet-browser defined facets and fallback to the camping
 * configured facets.
 *
 * @param bool $reset
 *   If TRUE cache is reset (default: FALSE).
 *
 * @return array
 *   The facets made available for this module.
 */
function _ding_campaign_plus_facet_get_facets($reset = FALSE) {
  $facets = &drupal_static(__FUNCTION__, array());

  if (empty($facets) || $reset) {
    $facets = variable_get('ding_campaign_plus_facets', NULL);
    if (is_null($facets)) {
      $facets = variable_get('ding_facetbrowser_facets', array());
      $facets = array_map(function ($facet) {
        return array(
          'facet' => $facet['name'],
          'title' => $facet['title'],
          'weight' => $facet['weight'],
        );
      }, $facets);
    }
  }

  return $facets;
}

/**
 * Build facets used in search queries.
 *
 * This is an combination of the default facets combined with the facets defined
 * in the administration interface in this module.
 *
 * @param bool $reset
 *   If TRUE cache is reset (default: FALSE).
 *
 * @return array
 *   The facets that should be used to check if facet campaign can be triggered.
 */
function _ding_campaign_plus_facet_build_search_facets($reset = FALSE) {
  $facets = &drupal_static(__FUNCTION__, array());

  if (empty($facets) || $reset) {
    if (module_exists('ding_facetbrowser')) {
      // Populate facets with configured facets.
      foreach (variable_get('ding_facetbrowser_facets', array()) as $facet) {
        $facets[] = $facet['name'];
      }
    }
    else {
      // Fallback to the CMS's default facets as defined in the ting client.
      $facets = array(
        'facet.subject',
        'facet.creator',
        'facet.type',
        'facet.category',
        'facet.language',
        'facet.date',
        'facet.acSource',
      );
    }

    // Merge the campaign plus facet into default facets.
    $campaign_facets = variable_get('ding_campaign_plus_facets', NULL);
    if (!is_null($campaign_facets)) {
      foreach ($campaign_facets as $campaign_facet) {
        if (!in_array($campaign_facet['facet'], $facets)) {
          $facets[] = $campaign_facet['facet'];
        }
      }
    }
  }

  return $facets;
}

/**
 * Helper function to look-up rules in the database.
 *
 * @param string $keys
 *   Search keys entered by the user.
 *
 * @return array
 *   Matches indexed by facet name and contains campaign ID's.
 */
function _ding_campaign_plus_facet_match($keys) {
  $triggers = array();

  // Find rules that will match facet.
  $campaigns = db_select('ding_campaign_plus_facet', 'dcpf')
    ->fields('dcpf')
    ->execute();

  if ($campaigns) {
    // Run user search - to get facets.
    $facet_array = array();
    $conditions = ting_search_conditions_callback($keys);
    $query = '(' . _ting_search_quote($keys) . ')';

    // Extend query with selected facets.
    if (isset($conditions['facets']) && $conditions['facets'] != NULL) {
      $facets = $conditions['facets'];
      foreach ($facets as $facet) {
        $facet = explode(':', $facet, 2);
        if ($facet[0]) {
          $facet_array[] = $facet[0] . '="' . rawurldecode($facet[1]) . '"';
        }
      }

      $query .= ' AND ' . implode(' AND ', $facet_array);
    }

    module_load_include('client.inc', 'ting');
    $search_result = ting_do_search($query, 1, 1, array(
      'numFacets' => variable_get('ting_search_number_of_facets', 25),
      'facets' => _ding_campaign_plus_facet_build_search_facets(),
    ));

    // Loop rules to find most common matches in facets.
    foreach ($campaigns as $campaign) {
      $facets = (array) unserialize($campaign->value);
      if (isset($search_result->facets[$campaign->facet])) {
        $terms = $search_result->facets[$campaign->facet]->terms;

        // Cut off all terms above the current triggers "most common" limit. The
        // array keys are extracted as some facets has numbers as keys and it's
        // the keys that are the facet names. The array slice will assume that
        // strings as number are numbers a will reset theme. Which is not what
        // we wan't here.
        $terms = array_keys($terms);
        $terms = array_slice($terms, 0, $campaign->common);

        // Check if facets matches any of the terms left.
        foreach ($facets as $facet) {
          $facet = drupal_strtolower($facet);
          if (in_array($facet, $terms)) {
            if (!isset($triggers[$facet])) {
              $triggers[$campaign->facet] = array();
            }
            $triggers[$campaign->facet][] = $campaign->nid;
            break;
          }
        }
      }
    }
  }

  return $triggers;
}

/**
 * Implements hook_ding_campaign_plus_validator().
 *
 * Validate that a give campaign triggers don't have 0-hits in the search
 * query.
 */
function ding_campaign_plus_facet_ding_campaign_plus_validator($nid) {
  $triggers = db_select('ding_campaign_plus_facet', 'dcpf')
    ->fields('dcpf')
    ->condition('nid', $nid)
    ->execute()
    ->fetchAll();

  if ($triggers) {
    $active = TRUE;
    module_load_include('client.inc', 'ting');
    foreach ($triggers as $trigger) {
      $facet_array = array();
      $facets = (array) unserialize($trigger->value);
      foreach ($facets as $facet) {
        $facet_array[] = $trigger->facet . '="' . rawurldecode($facet) . '"';
      }
      $query = implode(' AND ', $facet_array);
      $search_result = ting_do_search($query, 1, 1);

      if ($search_result->numTotalObjects > 0) {
        // No need to check more rules one of theme makes hits.
        return TRUE;
      }
      else {
        $active = FALSE;
      }
    }

    return $active;
  }

  return NULL;
}
