<?php

/**
 * @file
 * Lifecycle handling for Ding React apps.
 */

/**
 * Implements hook_uninstall().
 */
function ding_react_uninstall() {
  variable_del('ding_react_material_list_url');
  variable_del('ding_react_follow_searches_url');
  variable_del('ding_react_migrate_timeout');
  variable_del('ding_react_debug');
}

/**
 * Delete the openlist_uid from ting_openlist.
 */
function ding_react_update_7101() {
  db_drop_field('users', 'openlist_uid');
}
