<?php

/**
 *
 */
function ding_periodical_reservation_button($id, $volume, $issue, $entity) {
  return drupal_render(ding_provider_get_form('ding_reservation_reserve_form', new DingPeriodicalReservable($id, $volume, $issue, $entity)));
}

/**
 * A periodical reservation.
 */
class DingPeriodicalReservable implements DingReservationReservable {
  public function __construct($id, $volume, $issue, $entity) {
    $this->id = $id;
    $this->volume = $volume;
    $this->issue = $issue;
    $this->entity = $entity;  
  }

  public function getProviderId() {
    // pjo 16-01-12 reservations did not work for alma-periodicals;
    // switch on provider type
    $type = ding_provider_get_provider_module_name('reservation');
    switch($type) {
    case 'openruth' :
      return array($this->entity->provider_id, $this->id);
    case 'alma' :
      return $this->id;
    default:
      return $this->id;
    }   
  }

  public function getEntity() {
    return $this->entity;
  }

  public function getTitle() {
    return t('@title, vol @volume, issue @issue', array('@title' => $this->entity->title, '@volume' => $this->volume, '@issue' => $this->issue));
  }
}
