<?php
/**
 * @file
 * Ding user complete test cases.
 */

/**
 * Implements hook_menu().
 */
function ding_user_complete_test_menu() {
  $items = array();
  $items['ding/user-complete/confirm-data/%ctools_js/%user'] = array(
    'title' => 'Ding user complete test',
    'page callback' => 'ding_user_complete_test_confirm_data_callback',
    'page arguments' => array(3, 4),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_confirm_data_callback().
 */
function ding_user_complete_test_confirm_data_callback($ajax, $account) {
  $commands = array();

  $account = user_load($GLOBALS['user']->uid);

  $account->data['ding_user_complete_test_confirm'] = time();

  user_save($account);

  $identifier = '.user-barometer-tip .actions';
  $output = '<div class="actions">Tak for din bekræftelse, husk du altid kan ændre dine oplysninger under din profil.</div>';

  $commands[] = ajax_command_replace($identifier, $output);

  print ajax_render($commands);
  exit;
}

/**
 * Implements hook_user_complete().
 */
function ding_user_complete_test_user_complete() {
  ctools_include('ajax');

  // Implement custom logic here to tell whether
  // the user has completed this point step or not.
  $is_complete = FALSE;

  // Implement custom point definition here.
  $set['test_implementation'] = array(
    'title' => 'User complete test point 1',
    'points' => 5,
    'completed' => $is_complete,
    'markup' => 'Markup to show when completed is false',
  );

  // Implement custom logic here to tell whether the
  // user has completed this point step or not.
  $is_complete = FALSE;
  global $user;

  $title = t('Bekræft');
  $path = 'ding/user-complete/confirm-data/nojs/' . $user->uid;

  if (isset($user->data['ding_user_complete_test_confirm'])
    && $user->data['ding_user_complete_test_confirm'] > time() - 30
  ) {
    $is_complete = TRUE;
  }

  // Implement custom point definition here.
  $set['another_implementation'] = array(
    'title' => 'Er din email korrekt?',
    'points' => 10,
    'completed' => $is_complete,
    'markup' => "<div class='description'>" . t('Vi har noteret at din email er test@ok.dk og dit telefonnummer er 12345678.') . "</div><ul class='actions'><li>" . l(t('Ret mine personlige oplysninger'), "user/{$user->uid}/edit") . "</li><li>" . ctools_ajax_text_button($title, $path, $title, "") . "</li></ul>",
  );

  return $set;
}
