<?php
/**
 * @file
 * Code for the Ding paragraphs feature.
 */

include_once 'ding_paragraphs.features.inc';

/**
* Implements hook_preprocess_entity().
*/
function ding_paragraphs_preprocess_node(&$variables) {
  if (isset($variables['field_ding_news_paragraphs']) || isset($variables['field_ding_page_paragraphs']) ) {
    drupal_add_library('system', 'drupal.ajax');
    drupal_add_library('system', 'ui.widget');
    drupal_add_js(drupal_get_path('module', 'ding_paragraphs') .'/js/ding_paragraphs.js', 'file');
    drupal_add_js(drupal_get_path('module', 'ding_availability') . '/js/ding_availability.js', 'file');
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function ding_paragraphs_entity_info_alter(&$entity_info) {
  $entity_info['ting_object']['view modes'] += array(
    'paragraphs_teaser' => array(
      'label' => t('Paragraphs teaser'),
      'custom settings' => TRUE,
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add js for form.
 */
function ding_paragraphs_form_node_form_alter(&$form, &$form_state) {
  // General form setup.
  $form['#attached'] = array(
    'js' => array(
      array(
        'type' => 'file',
        'data' => drupal_get_path('module', 'ding_paragraphs'). '/js/ding_paragraphs_form.js',
      ),
    )
  );
}